### ISSUE TITLE
Why :tap create additional spring boot application and 4 kafka queues

### ISSUE THREAD

**Issue by surverohan** [spring-cloud/spring-cloud-dataflow#1700] opened 2017-10-18 18:41 UTC
So - source
p - processor
s - sink

Use-case for creating data flow

1) for new record flow should so => s
2) for update records flow should be so => p => s

DSL:
demo1=so|p > :foo
demo2=:demo1.so > :foo
demo3=:foo > s

After implementing this logic I have seen that scdf creates  2 additional queue for demo1.so and foo and also one spring boot application binder which is running on client server and trying to share resources from actual application and regular kafka queues

**Comment by sabbyanandan** [comment] 2017-10-21 17:06
This is a duplicate of a StackOverflow thread answered [here](https://stackoverflow.com/questions/46817011/is-this-bug-in-spring-cloud-data-flow-tab-create-2-additional-kafka-queues-and/46865782#46865782). 

For questions, please use StackOverflow and it'd be great if you can avoid cross-posting the same issue in multiple forums.

**Closed by sabbyanandan** 2017-10-21 17:06 UTC
Labels: question
