### ISSUE TITLE
After migration from S.Boot 2.7 -> 3.1, and SBatch 4... -> 5 the error "Caused by: org.postgresql.util.PSQLException: ERROR: relation "boot3_task_execution" does not exist" is thrown

### ISSUE THREAD

**Issue by Setxand** [spring-cloud/spring-cloud-dataflow#5597] opened 2023-12-07 15:20 UTC
Before the Migration everything was ok, and the batch jobs worked well, after this migration we upgraded SCDF to 2.11.1-jdk17, and everything is ok, except of one thing, here is the stack trace: 

`org.springframework.context.ApplicationContextException: Failed to start bean 'taskLifecycleListener'
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:958)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:611)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at com.tui.destimint.download.atcomres.AtComResDownloadApp.main(AtComResDownloadApp.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
	Caused by: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT TASK_EXECUTION_ID, START_TIME, END_TIME, TASK_NAME, EXIT_CODE, EXIT_MESSAGE, ERROR_MESSAGE, LAST_UPDATED, EXTERNAL_EXECUTION_ID, PARENT_EXECUTION_ID from BOOT3_TASK_EXECUTION where TASK_EXECUTION_ID = ?]
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:104)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1572)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:738)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:794)
	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.queryForObject(NamedParameterJdbcTemplate.java:246)
	at org.springframework.cloud.task.repository.dao.JdbcTaskExecutionDao.getTaskExecution(JdbcTaskExecutionDao.java:298)
	at org.springframework.cloud.task.repository.support.SimpleTaskExplorer.getTaskExecution(SimpleTaskExplorer.java:54)
	at org.springframework.cloud.task.listener.TaskLifecycleListener.doTaskStart(TaskLifecycleListener.java:274)
	at org.springframework.cloud.task.listener.TaskLifecycleListener.start(TaskLifecycleListener.java:411)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179)
	... 20 common frames omitted
	Caused by: org.postgresql.util.PSQLException: ERROR: relation "boot3_task_execution" does not exist
  Position: 162
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:648)
	... 29 common frames omitted`.     

We're using not the default schema there, and set it with '?currentSchema=' param in the db URL for the SCDF and the batch job, 

the first thing I thought is the schema is set incorrectly and the batch job uses the default schema, but here is the logs , and here the schema is correct, and in the end you can see the Application failed log with the stack trace above

**Comment by corneil** [comment] 2023-12-10 12:17
Hi @Setxand,
This seems to be related to a problem we identified with the JobService.
A fix was merged into `main`. 
Please try the latest snapshot and let us know.

**Comment by corneil** [comment] 2023-12-11 08:20
Your stack trace shows `Caused by: org.postgresql.util.PSQLException: ERROR: relation "boot3_task_execution" does not exist Position: 162 at` you need to allow SCDF to create the database schema needed for the task and batch applications.
If you are using a different schema in the batch application than what dataflow is using then it should be treated the same as multiple datasources. This is not advisable at this point since we are planning work to improve the management and handling of multiple datasources.

**Comment by Setxand** [comment] 2023-12-13 05:23
Hi @corneil , thanks for answer, It's allowed, and flyway created the boot3 tables before the execution of the job, but I've found the issue - it looks spring boot tried to create the different datasource from (I don't have an idea why) defined in applicaiton.yml, can it be overridden properties from SCDF when launching the app? IDK, but when I defined the custom datasource in the spring boot app - the issue is solved and the job used the correct schema boot3 tables are created in

**Comment by corneil** [comment] 2023-12-18 09:58
The datasource info provided in the application environment will override settings from your application.yml

**Closed by corneil** 2023-12-18 09:58 UTC
Labels: for/team-attention
