### ISSUE TITLE
Task Launch command only executes boot apps that are tasks

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#244] opened 2015-12-16 14:43 UTC
The user wants the task launch command to execute only boot apps that are tasks.  
- If boot app is not marked to be a task, i.e. by `@EnableTask` or TaskApplication, then an error message will be displayed to the user.

**Comment by mminella** [comment] 2016-01-29 20:09
Duplicate of 287

**Closed** 2016-01-29 20:08 UTC
