### ISSUE TITLE
How can I pass arguments that contain "," in command line?

### ISSUE THREAD

**Issue by ding-kai** [spring-cloud/spring-cloud-dataflow#1826] opened 2017-12-07 09:21 UTC
As i noticed that the arguments was divided by "," .
> dataflow:>task launch mytask --arguments "--server.port=8080,--foo=bar"

Then  my arguments like "--keys=V1,V2,V3" pass error. 
How can I pass arguments that contain "," in command line?

Thanks.

**Comment by cppwfs** [comment] 2017-12-07 17:35
With Spring Cloud Data Flow we uses spaces to delimit arguments.   For
example in your example you are using a comma to delimit the
arguments.  dataflow:>task
launch mytask --arguments "--server.port=8080,--foo=bar"   Instead you
could do this:
dataflow:>task launch mytask --arguments "--server.port=8080 --foo=bar
--keys=a,b,c"

--Glenn

**Comment by ding-kai** [comment] 2017-12-08 05:44
But I see the following in the [reference(v1.2.3)](https://docs.spring.io/spring-cloud-dataflow/docs/1.2.3.RELEASE/reference/htmlsingle/#_launching_a_task)

> When a task is launched, any properties that need to be passed as the command line arguments to the task application can be set when launching the task as follows:
> `dataflow:>task launch mytask --arguments "--server.port=8080,--foo=bar"`

I tried as you said, and it still not work.
The command line is as follows,
![command line](https://raw.githubusercontent.com/ding-kai/issues-images-repository/master/images/20171208103609.png)
and the arguments 'keys' on dashboard got 'V1' but not 'V1,V2,V3'.
![dashboard](https://raw.githubusercontent.com/ding-kai/issues-images-repository/master/images/20171208103654.png)

please help. Thanks.

**Comment by cppwfs** [comment] 2017-12-08 21:01
Had a chance to take a second look at this issue.  And you are correct.  The issue lies in how the `TaskExecutionLauncher.launch` method is accepting a list.   It is parsing each comma in the arguments parameter as a individual argument.  i.e.  `--keys=V1,V2,V3,--foo=moo,--bar=baz` is treated as an argument list as follows
* --keys=v1
* V2
* V3
* --foo=moo
* --bar=baz
We probably want to switch it to use a string and parse it ourselves where a user can add a \, for parameters that require a comma delimited list.   i.e. `--keys=V1\,V2\,V3,--foo=moo,--bar=baz`

**Comment by jvmlet** [comment] 2017-12-12 06:11
Please consider to support special escape character in argument/property value, because `,` is not the only character you want to escape,
 `deployer.local.javaOpts=-agentlib:jdwp=transport=dt_socket,server=n,address=localhost:5006,suspend=y` is another example where you want the `=` to be escaped as well.

**Comment by cppwfs** [comment] 2018-01-02 16:50
in this case you would want to use properties file instead of the arguments. i.e.   `task launch mytask --arguments "--server.port=8080 --foo=bar" --propertiesFile "/Users/glennrenfro/tmp/myprops.props"`.
with the contents:
```
app.mytask.AAA.keys=a,b,c
```

**Comment by sabbyanandan** [comment] 2018-01-08 00:29
Hi, @ding-kai/@jvmlet. The use of a property/yaml file is the recommended approach to supply k/v props that include special characters. See the example attached to the previous comment. Alternatively, you can use the config-server to resolve such properties from the remote repositories, too.

Since we aren't planning to address anything other than what's already supported, I will close this.

**Comment by youarehow** [comment] 2018-05-24 20:32
The properties file approach suggested above is very intrusive and hopefully we can have a better method.

We were using TaskOperations interface to launch task and also found arguments with comma were not properly handled when the launch request reaches the TaskExecutionController's REST point. In particluar, this method:

	@RequestMapping(value = "", method = RequestMethod.POST, params = "name")
	@ResponseStatus(HttpStatus.CREATED)
	public long launch(@RequestParam("name") String taskName, @RequestParam(required = false) String properties,
			@RequestParam(required = false) List<String> arguments) {
		Map<String, String> propertiesToUse = DeploymentPropertiesUtils.parse(properties);
		DeploymentPropertiesUtils.ensureJustDeploymentProperties(propertiesToUse);
		return this.taskService.executeTask(taskName, propertiesToUse,
				DeploymentPropertiesUtils.parseParams(arguments));
	}
As you can see the properties is a single string and SCDF then parse it into a Map, this already means the properties need to built based on some delimiter. The arguments list works fine when there is no argument with comma but not when comma is involved. After further investigation, it all boils down to how TaskTemplate (which implements TaskOperations) packs the properties and arguments. Here is the code:

	@Override
	public long launch(String name, Map<String, String> properties, List<String> arguments) {
		MultiValueMap<String, Object> values = new LinkedMultiValueMap<>();
		values.add("properties", DeploymentPropertiesUtils.format(properties));
		values.add("arguments", StringUtils.collectionToDelimitedString(arguments, " "));
		return restTemplate.postForObject(executionByNameLink.expand(name).getHref(), values, Long.class, name);
	}
As you can see, SCDF merges the properties to one line and also arguments as one line. For the arguments list variable, the following code stack in the controller side before it reaches the above mentioned method is invoked: RequestParamMethodArgumentResolver->ExtendedServletRequestDataBinder->StringToCollectionConverter. The StringToCollectionConverter parses this single argument line using comma. That is where things go wrong.

Then I sit back to ask why we are doing all these merging and then unpack thing. So I created a single class:
public class LaunchTaskRequest implements Serializable {
  private Map<String, String> taskDeploymentProperties;
  private List<String> commandLineArgs;
  //...getters setters omitted ....
}

Added a customized controller with the following:
  @RequestMapping(value = "", method = RequestMethod.POST, params = "name")
  @ResponseStatus(HttpStatus.CREATED)
  public long launch(@RequestParam("name") String taskName,
      @RequestBody(required = false) LaunchTaskRequest launchTaskRequest) {
    Map<String, String> propertiesToUse =
        launchTaskRequest == null || launchTaskRequest.getTaskDeploymentProperties() == null
            ? new HashMap<String, String>()
            : launchTaskRequest.getTaskDeploymentProperties();
    DeploymentPropertiesUtils.ensureJustDeploymentProperties(propertiesToUse);
    return this.taskService.executeTask(taskName, propertiesToUse,
        launchTaskRequest == null ? new ArrayList<String>() : launchTaskRequest.getCommandLineArgs());
  }

Added a customized TaskTemplate method:

  public long launch(String name, Map<String, String> properties, List<String> arguments)
  {
    String resourcePath = .... omitted ....
    LaunchTaskRequest launchTaskRequest = new LaunchTaskRequest();
    launchTaskRequest.setCommandLineArgs(arguments);
    launchTaskRequest.setTaskDeploymentProperties(properties); <-- pack them into the wrapper
    return postForEntity(resourcePath, launchTaskRequest, Long.class);
  }

Now it all works fine. The Jackson will map the LaunchTaskRequest into JSON and it is properly deserialized in the customized REST point. It now handles the comma or equal sign without problem. 

I am guessing the reason behind the combining logic of the TaskTemplate is just because TaskExecutionController provides such API. Had TaskExecutionController have a wrapper based argument, then the properties Map and arguments List should have been passed around well. 

Just threw this findings here and hopefully it can benefit someone.

**Comment by tzolov** [comment] 2018-05-30 13:50
@youarehow, thank you for your research! 
I can confirm that the task deployment arguments can't handle commas (and possibly other uri sensitive characters). 
Will investigate further to see if there is a fix that wouldn't introduce API backward incompatible changes.

**Comment by youarehow** [comment] 2018-05-30 20:44
@tzolov Glad it helps. Thanks for looking into this!

**Closed** 2018-06-01 19:51 UTC
Labels: in pr
