### ISSUE TITLE
Stopping a batch with Spring Boot 3/Spring Batch 5 doesn't work properly.

### ISSUE THREAD

**Issue by khaeghar** [spring-cloud/spring-cloud-dataflow#5520] opened 2023-10-19 15:26 UTC
**Description:**
When using the STOP function of SCDF, the SCDF fails with the following message:

```
2023-10-19 09:25:33.460 INFO [http-nio-8081-exec-6] [org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService] getJobExecution:59:boot3
2023-10-19 09:25:48.931 WARN [http-nio-8081-exec-1] [org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver] Failed to retrieve properties for resource Docker Resource [docker:.../.../apabatch:] because of ContainerRegistryException: Could not find an Registry Configuration for: registry.san.dev.weu.azure.paas.cloudcenter.corp
2023-10-19 09:25:48.931 WARN [http-nio-8081-exec-1] [org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver] Failed to retrieve port names for resource Docker Resource [docker:.../.../apabatch] because of ContainerRegistryException: Could not find an Registry Configuration for: registry.san.dev.weu.azure.paas.cloudcenter.corp
2023-10-19 09:25:48.932 WARN [http-nio-8081-exec-1] [org.springframework.cloud.dataflow.configuration.metadata.BootApplicationConfigurationMetadataResolver] Failed to retrieve port names for resource Docker Resource [docker:.../.../apabatch] because of ContainerRegistryException: Could not find an Registry Configuration for: registry.san.dev.weu.azure.paas.cloudcenter.corp
2023-10-19 09:25:48.941 ERROR [http-nio-8081-exec-3] [org.springframework.cloud.dataflow.server.controller.RestControllerAdvice] Caught exception while handling a request
org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT JOB_EXECUTION_ID, KEY_NAME, TYPE_CD, STRING_VAL, DATE_VAL, LONG_VAL, DOUBLE_VAL, IDENTIFYING from BOOT3_BATCH_JOB_EXECUTION_PARAMS where JOB_EXECUTION_ID = ?]; nested exception is org.postgresql.util.PSQLException: ERROR: column "key_name" does not exist
Position: 26
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:101)
```

**Release versions:**
 SCDF 2.11

**Custom apps:**

**Steps to reproduce:**

1. Execute a Job
2. Try to stop it with SCDF

**Comment by cppwfs** [comment] 2023-11-16 15:21
Using the SCDF Local deployer with a Postgresql, I was unable to reproduce this issue.  Can you share:
* Postgres version
* Deployer (Kubernetes, CF, Local)

**Comment by cppwfs** [comment] 2023-11-16 16:42
I was able to reproduce!

**Comment by corneil** [comment] 2023-12-04 13:33
Looks like the query is batch 4 job parameters schema against batch 5 table.

**Comment by cppwfs** [comment] 2023-12-20 22:00
Closed via https://github.com/spring-cloud/spring-cloud-dataflow/pull/5581

**Closed by cppwfs** 2023-12-20 22:00 UTC
Labels: type/bug
