### ISSUE TITLE
Register cron expression based on timezone of SCDF Server.

### ISSUE THREAD

**Issue by 23king** [spring-cloud/spring-cloud-dataflow#4303] opened 2020-12-29 01:02 UTC
Problem description:

The timezone between Cloud Platform's cron expression and Spring Cloud Data Flow Server's cron expression does not match.

Solution description:
In the k8s configMap, specify the timezone of the k8s platform. And when registering the schedule, modify the cron expression by referring to the timezone of the k8s platform.

apiVersion: v1
kind: ConfigMap
metadata:
  name: scdf-server
  labels:
    app: scdf-server
data:
  application.yaml: |-
    management:
      metrics:
        export:
          prometheus:
            enabled: true
            rsocket:
              enabled: true
              host: prometheus-proxy
              port: 7001
    spring:
      cloud:
        dataflow:
          metrics.dashboard:
            url: 'https://grafana:3000'
          task:
            platform:
              **timezone: UTC**
              kubernetes:
                accounts:
                  default:
                    limits:
                      memory: 1024Mi
      datasource:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST}:${MYSQL_SERVICE_PORT}/mysql
        username: root
        password: ${mysql-root-password}
        driverClassName: org.mariadb.jdbc.Driver
        testOnBorrow: true
        validationQuery: "SELECT 1"

Description of alternatives:
N/A

Additional context:
I have already modified the code. We'll share your edits through Pull Requests.

**Comment by jvalkeal** [comment] 2021-01-01 00:09
Could you restructure this issue in a more consumable description so that we'd know what you are trying to accomplish. I'd very much like to see a use case, problem and then a possible discussion about a possible solution to a problem.

Unfortunately a related PR is contains unneeded changes and a change to a dependencies(which we don't accept easily), so I need to reject it for now.

**Comment by 23king** [comment] 2021-01-01 00:38
AS-IS:
If the timezone of the scdf server is asia/seoul and the timezone of k8s is UTC,
When registering a schedule with cron, if it is registered as a timezone based on asia/seoul, the operation operates in the UTC timezone, which is the timezone of k8s.

TO-BE:
When the timezone of the scdf server is asia/seoul and the timezone of k8s is UTC
When cron schedule is registered as asia/seoul, cron expression is converted into UTC standard and registered.

It is the same content as issue #4111.

**Comment by 23king** [comment] 2021-01-08 20:41
@jvalkeal  
Please give me feedback. I need this feature wherever I am using it.

**Comment by sabbyanandan** [comment] 2021-01-14 18:26
Hi, @23king. Thanks for your contribution.  As @jvalkeal pointed out, could you resubmit a PR with just the changes associated with overriding the timezone, and just that, please? 

@jvalkeal: I do see value in being able to adjust the timezone when launching the task. Once when we have the new PR, please have a look and let us know your findings.

**Comment by cppwfs** [comment] 2021-01-22 18:34
@23king Thank you for your contribution.   We do appreciate it.   However, we had a discussion on this topic today, and decided that do not wish to convert the schedule cron expression for each platform.   But rather store this timezone information for each platform.    The issue is located here: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4341

**Comment by 23king** [comment] 2021-03-22 21:47
Good news~

**Comment by ThibaultDelaune-pro** [comment] 2021-03-23 09:45
Hi, I do have the same use case on my projects. Our Data Flow platform is in the `Europe/Paris` timezone while our K8s platform is in UTC (and can't be changed).
In this timezone, we have change of time twice a year (UTC+1 in winter and UTC+2 in summer).
So currently, the only choice we have is to manually change our scheduled tasks cron expression twice a year.
This PR is really expected.
Thanks.

**Comment by cppwfs** [comment] 2021-04-13 16:00
Closing this Issue.  The solution enumerated in  https://github.com/spring-cloud/spring-cloud-dataflow/issues/4476 is the preferred method.

**Closed by cppwfs** 2021-04-13 16:00 UTC
Labels: for/team-attention, status/need-design

**Comment by ThibaultDelaune-pro** [comment] 2021-04-22 07:51
Sorry but I don't see how the solution enumerated in #4476 would solve my problem?!?
This is not an information issue but a runtime issue.
Even if I knew which timezone the platform is associated (in my case UTC), it wouldn't start my task in the correct time (in my case UTC+1 or UTC+2)!
Please reconsider this PR.

**Comment by ThibaultDelaune-pro** [comment] 2021-04-22 07:58
Would it be possible to make SCDF launch [TZCronjob](https://github.com/hiddeco/cronjobber) instead of Cronjob?

**Comment by 23king** [comment] 2021-04-22 09:09
> Would it be possible to make SCDF launch [TZCronjob](https://github.com/hiddeco/cronjobber) instead of Cronjob?

SCDF is just only serve to register the cron cloudPlatform. Do not use the cronjob in SCDF.
