### ISSUE TITLE
Kubernetes Launch Task Issue(Exec and Boot)

### ISSUE THREAD

**Issue by umutcann** [spring-cloud/spring-cloud-dataflow#4205] opened 2020-10-17 09:20 UTC
Hi,

I'm facing restart task problem due to  #4199 . As I understand, this problem is occurring when entry point style is _shell_.

So that, I tried to launch task using _exec_ and _boot_ as entry point style. Then I got errors like below.

**boot**

(combined from similar events): Error: container create failed: time="2020-10-17T09:11:18Z" level=error msg="container_linux.go:349: starting container process caused \"exec: \\\"--spring.cloud.task.executionid=13704\\\": executable file not found in $PATH\"" container_linux.go:349: starting container process caused "exec: \"--spring.cloud.task.executionid=13704\": executable file not found in $PATH"

**exec**

Error: container create failed: time="2020-10-17T09:13:02Z" level=error msg="container_linux.go:349: starting container process caused \"exec: \\\"--management.metrics.tags.service=task application\\\": executable file not found in $PATH\"" container_linux.go:349: starting container process caused "exec: \"--management.metrics.tags.service=task application\": executable file not found in $PATH"

Do you have any idea regarding those problems?

**Comment by cppwfs** [comment] 2020-10-19 15:32
Hello @umutcann.  How did you create your container?

**Comment by cppwfs** [comment] 2020-10-20 18:51
Hello @umutcann I was able to reproduce your issue using Spring-Boots build-image to create containers for tasks.   After working with the boot team we were able to identify 2 issues:
1) The first was resolved here: https://github.com/spring-projects/spring-boot/issues/23692
2) The second will be resolved here: https://github.com/buildpacks/lifecycle/issues/445
If my assumption is correct that you were using Spring Boots `build-image` then we can close this issue once buildpacks fixes this issue and does a release.   
However if you were not using `build-image`  how were you building your containers?

**Comment by umutcann** [comment] 2020-10-21 07:46
Hi @cppwfs 

We are building image on openshift. We have build [configs](https://docs.openshift.com/container-platform/4.2/builds/understanding-buildconfigs.html). Our image build type is [s2i](https://docs.openshift.com/enterprise/3.0/architecture/core_concepts/builds_and_image_streams.html#source-build).

I hope that I might answer your question.

As I understand, we need to update SCDF again, right?

**Comment by cppwfs** [comment] 2020-10-21 15:23
Hmm.   I'm not sure this is a dataflow issue as much as a container issue.    Have you tried to execute the container using `docker run` using command line args to establish the properties for the task to test your container?   i.e.

```
docker run  myapp:latest --management.metrics.tags.service=task application --spring.datasource.username=root --management.metrics.export.prometheus.enabled=true --spring.datasource.url=jdbc:mysql://<uri to acceible db>:3306/mysql --spring.datasource.driverClassName=org.mariadb.jdbc.Driver --management.metrics.tags.application=foo-bar --management.metrics.export.prometheus.rsocket.port=7001 --management.metrics.export.prometheus.rsocket.enabled=true --spring.cloud.task.name=pt1019a --management.metrics.export.prometheus.rsocket.host=prometheus-proxy --spring.datasource.password=yourpassword cup=dynamic my=stuff more=stuff yet=morestuff cool=stuff --noidentifiable=stuff identifiable=stuff
```

Or if you have H2 as a dependency in your build file should be able to run it without datasource:
```
docker run  myapp:latest --management.metrics.tags.service=task application --management.metrics.export.prometheus.enabled=true  --management.metrics.tags.application=foo-bar --management.metrics.export.prometheus.rsocket.port=7001 --management.metrics.export.prometheus.rsocket.enabled=true --spring.cloud.task.name=pt1019a --management.metrics.export.prometheus.rsocket.host=prometheus-proxy my=stuff more=stuff yet=morestuff cool=stuff --noidentifiable=stuff identifiable=stuff
```

**Comment by umutcann** [comment] 2020-10-26 08:05
Hi @cppwfs 

We got same error when we run docker command. 

The problem is related with docker not scdf, right?

**Comment by cppwfs** [comment] 2020-10-26 12:43
Well not necessarily docker but rather how the the container is build using S2I.
You can try to build your image using Spring Boot's Docker Image builder.   For an experiment you can try using Spring Boot 2.4-SNAPSHOT as your project parent (not for production, just POC) and create your image with the following `./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=<yourname>:yourtag` as shown in the getting started guide here:   https://spring.io/guides/gs/spring-boot-docker/.

*Notice I'm using the SNAPSHOT, because boot has updated the container such that it can accept command line args*

**Comment by cppwfs** [comment] 2020-11-02 20:05
@umutcann I'm closing this issue for now.  If you have additional information we can reopen it.

**Closed by cppwfs** 2020-11-02 20:05 UTC
Labels: waiting-for-feedback
