### ISSUE TITLE
Resizing browser results in bad layout of docs

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#1066] opened 2016-12-15 14:50 UTC
The browser needs to be very wide to see all the text and if you shrink the brower's width, the text flows off the left hand side.

If you look at http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/  when the browser is resized, the text reflows.

**Comment by donovanmuller** [comment] 2016-12-15 15:06
Possible duplicate of #1044?

**Comment by sabbyanandan** [comment] 2016-12-19 15:52
This was caused due to "search bar" add-on at the bottom and that has been removed from all the reference guides.

**Closed by sabbyanandan** 2016-12-19 15:52 UTC
Labels: ready
