### ISSUE TITLE
SCDF doesn't close connections to postgress database

### ISSUE THREAD

**Issue by Rostish** [spring-cloud/spring-cloud-dataflow#2625] opened 2018-11-29 08:52 UTC
**Description:**
Have found a strange behavior with the interaction of the SCDF and postgress database which contains task/job/execution data.
After a couple of scheme executions, my task started to fall with the next error:

![image](https://user-images.githubusercontent.com/15521647/49208339-95617100-f3c8-11e8-9895-2bb7967ad185.png)
I have interacted with database operations department and they said it connect with idled connections:

![image](https://user-images.githubusercontent.com/15521647/49208627-55e75480-f3c9-11e8-8cbb-26de0d392aab.png)
10.101.53.100 - this is an adress where is SCDF deployed. 

All task which were executed without any error and end their work normally.
![image](https://user-images.githubusercontent.com/15521647/49208734-9a72f000-f3c9-11e8-871b-7ad23bfbc6d4.png)

**If reboot SCDF and start again all problems are gone.**

**Custom apps:**
My task app do some data modification and save it to another storages. I have an app that controls creation of new task definition and task launching. It uses different REST methods like:
```
    @Override
    public Boolean isTaskComposed(String schemeName) throws JSONException {
        HttpHeaders headers = getHttpHeaders(scdfProperties);
        String requestUri = String.format("%1$s:%2$s/tasks/definitions/%3$s", scdfProperties.getRootUrl(), scdfProperties.getPort(),schemeName);
        HttpEntity<String> requestEntity = new HttpEntity<>(headers);

        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> responseEntity = restTemplate.exchange(
                requestUri,
                HttpMethod.GET,
                requestEntity,
                String.class);

        JSONObject body = new JSONObject(responseEntity.getBody());

        return Boolean.valueOf(body.getString("composed"));
    }
```

It seems to be after calling such methods SCDF is going to find some values in database and then doesn't close connections.

**Steps to reproduce:**
1. Create some REST requests from an app to SCDF.
2. Look at idled connections.

**Versions**
https://user-images.githubusercontent.com/15521647/49155745-c68c6380-f32c-11e8-8d02-2e7c01fa75bc.png

**Comment by Rostish** [comment] 2018-11-29 20:29
About REST this is just my **assumption**. Because i can't found any others ideas why SCDF could open so much sessions to postgress DataBase. Inside my custom task there are no code that could access the database. Only SCDF remains. SCDF by his self write only meta information about task execution/job execution/new definition and etc. Only my REST methods could provoke SCDF to contact the database above the norm. Usually my REST methods trying to get resources from task/job execution points.

**Comment by sabbyanandan** [comment] 2018-11-29 22:50
OK, it is unclear what the cause is. We will retry it on our side. Also, if you have experience with Postgres, please consider contributing through fixes/improvements.

**Comment by Rostish** [comment] 2018-11-30 06:47
@sabbyanandan Ok, thank you!

**Comment by tzolov** [comment] 2018-11-30 09:15
@Rostish,  i haven't been able to reproduce the issue so far! 
I've been testing with repetitive execution of the timestamp tasks, together with repetitive hits of the task definition REST endpoints but the PSQL connection pool never exceeded the expected 10 connections: 
<img width="1557" alt="screen shot 2018-11-30 at 10 04 32 am" src="https://user-images.githubusercontent.com/1351573/49279540-0f0c6400-f488-11e8-8bc0-feaff3a1e055.png">

Could you please provide some further details such as:
* explain how did you created your SCDF Database schema tables? 
* list all REST endpoints you've been using? 
* how do you determine the idle connections? 
* are you experiencing this issue if you don't execute the tasks but just run the REST requests?

**Comment by Rostish** [comment] 2018-11-30 14:48
First of all i should say that i use splitted task. Often this error appears then 3 or 4 parralel tasks start.

1. SCDF tables have been created at first SCDF startup.
2.  I use next Rest endpoints one time to prepare my scheme:
```
    @Override
    public String getTaskId(String schemeName) throws JSONException {

        HttpHeaders headers = getHttpHeaders(scdfProperties);
        String requestUri = String.format("%1$s:%2$s/tasks/definitions/%3$s", scdfProperties.getRootUrl(), scdfProperties.getPort(), schemeName);
        HttpEntity<String> requestEntity = new HttpEntity<>(headers);

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> responseEntity = restTemplate.exchange(
                requestUri,
                HttpMethod.GET,
                requestEntity,
                String.class);

        JSONObject body = new JSONObject(responseEntity.getBody());

        return String.valueOf(body.getJSONObject("lastTaskExecution").getString("executionId"));
    }

    @Override
    public String getTaskStatus(String schemeName) throws JSONException {

        HttpHeaders headers = getHttpHeaders(scdfProperties);
        String requestUri = String.format("%1$s:%2$s/tasks/definitions/%3$s", scdfProperties.getRootUrl(), scdfProperties.getPort(), schemeName);
        HttpEntity<String> requestEntity = new HttpEntity<>(headers);

        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> responseEntity = restTemplate.exchange(
                requestUri,
                HttpMethod.GET,
                requestEntity,
                String.class);

        JSONObject body = new JSONObject(responseEntity.getBody());

        return String.valueOf(body.getString("status"));
    }

    @Override
    public String getJobStatus(String jobId) throws JSONException {

        HttpHeaders headers = getHttpHeaders(scdfProperties);
        String requestUri = String.format("%1$s:%2$s/jobs/executions/%3$s", scdfProperties.getRootUrl(), scdfProperties.getPort(), jobId);
        HttpEntity<String> requestEntity = new HttpEntity<>(headers);

        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> responseEntity = restTemplate.exchange(
                requestUri,
                HttpMethod.GET,
                requestEntity,
                String.class);

        JSONObject body = new JSONObject(responseEntity.getBody());

        return String.valueOf(body.getJSONObject("jobExecution").getString("status"));
    }

    @Override
    public String getJobId(String taskId) throws JSONException, InterruptedException {
        HttpHeaders headers = getHttpHeaders(scdfProperties);
        String requestUri = String.format("%1$s:%2$s/tasks/executions/%3$s", scdfProperties.getRootUrl(), scdfProperties.getPort(), taskId);
        HttpEntity<String> requestEntity = new HttpEntity<>(headers);

        RestTemplate restTemplate = new RestTemplate();
        ResponseEntity<String> responseEntity = restTemplate.exchange(
                requestUri,
                HttpMethod.GET,
                requestEntity,
                String.class);

        JSONObject body = new JSONObject(responseEntity.getBody());

        if (body.getJSONArray("jobExecutionIds").isNull(0)) {
            Thread.sleep(2000);
            while (body.getJSONArray("jobExecutionIds").isNull(0)) {
                responseEntity = restTemplate.exchange(
                        requestUri,
                        HttpMethod.GET,
                        requestEntity,
                        String.class);
                body = new JSONObject(responseEntity.getBody());
            }
        }
        return String.valueOf(body.getJSONArray("jobExecutionIds").get(0));
    }
```
3. database operation department do next linux command:
ps aux | grep postgress
4. no, if i do just rest requests there are no errors.

**Comment by cppwfs** [comment] 2018-12-03 22:02
@Rotish If you are using ComposedTaskRunner 2.0 add the following command line arg: `--spring.cloud.task.closecontextEnabled=true` to each CTR execution and see if that resolves your issue.

**Comment by Rostish** [comment] 2018-12-04 06:02
@cppwfs 
Thank you for your advice!
I am going to try test my executions with this parameter.

**Comment by Rostish** [comment] 2018-12-10 06:55
@sabbyanandan 
@cppwfs 
It seems all working correct now.
My team moved SCDF database to another server + i tried to use closecontextEnabled argument.

**Comment by cppwfs** [comment] 2018-12-10 14:04
Awesome news.  I'll close this issue then.

**Closed** 2018-12-10 14:04 UTC
Labels: in progress, question
