### ISSUE TITLE
Task error on missing platform when trying a job execution restart on previous failed step

### ISSUE THREAD

**Issue by PipBoy-Engineer** [spring-cloud/spring-cloud-dataflow#4152] opened 2020-09-17 17:51 UTC
**Description:**
Hi,
When trying to restart a Job of a task which has previously failed with the command shell (example : `job execution restart --id 45`), I've got the following exception :

`
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Did not find platform for taskName=[task-extract-ged] , taskId=[48]
Did not find platform for taskName=[task-extract-ged] , taskId=[48]
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Did not find platform for taskName=[task-extract-ged] , taskId=[48]
    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65)
    at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
    at org.springframework.web.client.RestTemplate.put(RestTemplate.java:478)
    at org.springframework.cloud.dataflow.rest.client.JobTemplate.executionRestart(JobTemplate.java:104)
    at org.springframework.cloud.dataflow.shell.command.JobCommands.executionRestart(JobCommands.java:109)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.base/java.lang.Thread.run(Thread.java:834)
`

Here is an example of the command I use to launch the task :
`task launch task-extract-ged --arguments "input=classpath:input.csv output=classpath:output.csv" --properties "deployer.task-extract-ged.kubernetes.imagePullPolicy=Always" --platformName "kubernetes"`

I tried to launch the task without --platformName in parameters, with 'default' or 'kubernetes' value but it always gives me the same exception when attempting to restart the failed job

Thanks in advance

**Release versions:**
[SCDF-about.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/5240914/SCDF-about.txt)

**Steps to reproduce:**
Always using Spring Cloud Dataflow Shell 2.6.1
- Launch a task with a Step which fails with command `task launch name-of-the-task`
- Once the corresponding Job has failed try to restart it with command `job execution restart --id execution-id`

**Additional context:**
I'm developping  on a microk8s v1.18.8 on ubuntu 18.04.5 LTS

**Comment by sabbyanandan** [comment] 2020-09-17 18:11
Thanks for the report, @PipBoy-Engineer. Could you also share the app that you're using? It'd help because we need to have a task to fail first, and then attempt to restart it. The platform account should be persisted and cycled on subsequent launches, but if it is not, then there's either a gap or a valid reason for it. 

Either way, we can have a look at it with your app.

**Comment by cppwfs** [comment] 2020-09-17 18:45
Are you deploying onto Kubernetes?
If so, what entrypoint are you using?

**Comment by cppwfs** [comment] 2020-09-17 20:43
If it is `shell` we have an existing issue: https://github.com/spring-cloud/spring-cloud-dataflow/issues/4119#issuecomment-694020282

**Comment by PipBoy-Engineer** [comment] 2020-09-18 08:46
> Thanks for the report, @PipBoy-Engineer. Could you also share the app that you're using? It'd help because we need to have a task to fail first, and then attempt to restart it. The platform account should be persisted and cycled on subsequent launches, but if it is not, then there's either a gap or a valid reason for it.
> 
> Either way, we can have a look at it with your app.

Please find enclosed a simple example Task app to reproduce.
[task-error-test.zip](https://github.com/spring-cloud/spring-cloud-dataflow/files/5244110/task-error-test.zip)
This example reads a List of strings and generates randomly some RuntimeException during item Processing.
I build the container task with `jib-maven-plugin` with command `mvn compile jib:build`


> What entrypoint are you using?

The entry point of the container created is : `[java, -cp, /app/resources:/app/classes:/app/libs/*, com.example.taskerrortest.TaskErrorTestApplication]`



> If it is `shell` we have an existing issue: #4119

I have the problem in `shell` yes but also using dashboard for lanching the task and restarting the failed job

As for #4119 the problem seems correlated yes.

**Comment by cppwfs** [comment] 2020-09-18 14:58
For now I'm going to close this issue as a duplicate of #4119.   Thanks for this issue and the additional information.

**Closed by cppwfs** 2020-09-18 14:58 UTC
Labels: waiting-for-feedback
