### ISSUE TITLE
Investigate Boot 2 upgrade issue in ShellCommandsTests

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow#2543] opened 2018-11-02 15:33 UTC

**Comment by jvalkeal** [comment] 2018-11-13 09:50
This indeed seem to be caused by core/boot trying to send `ApplicationReadyEvent` after context has already been closed(due to boot app run finishing ok). Weird, don't really know if this is a real issue or just some testing issues as that test class is a bit odd.

**Comment by ilayaperumalg** [comment] 2018-11-13 09:54
Isn't this what we fixed as https://github.com/spring-cloud/spring-cloud-dataflow/commit/34d746abf38095810d60d6e06703ae8be436f7d7 ?

**Comment by jvalkeal** [comment] 2018-11-13 09:58
No, just realised that it's coming from our `ShellCommandLineRunner` which is then closing a context and only after that boot is trying to send that `ApplicationReadyEvent`. I now remember that there were some changes in boot what comes for a app lifecycle events.

**Comment by sabbyanandan** [comment] 2018-11-26 17:39
@jvalkeal: What's your recommendation on this? Do we have to switch Shell to Boot 2.0?

**Closed** 2020-09-16 21:02 UTC
Labels: test-coverage
