### ISSUE TITLE
Question JobParameters (Spring Cloud Dataflow Kuberntes)

### ISSUE THREAD

**Issue by guichafy** [spring-cloud/spring-cloud-dataflow#2125] opened 2018-03-29 21:39 UTC
Hello everyone, when we run a job the database access parameters are exposed, is it possible to hide them or to avoid sending them?

![image](https://user-images.githubusercontent.com/9120686/38114841-3fb3dd0a-3380-11e8-852a-1754e824225c.png)

**Comment by mminella** [comment] 2018-03-29 21:45
That looks like you're configuring the database creds via command line args for your task.  That is not a secure method of transmitting them.  If you configure them as application properties, they won't show up that way.  Otherwise, you can use cloud config as well.  I'm closing this since it's not a bug.  Please use StackOverflow for these kinds of questions going forward.

**Closed by mminella** 2018-03-29 21:45 UTC

**Comment by guichafy** [comment] 2018-03-29 22:33
@mniella What's strange is that I did not set any parameters in the job definition and even then the launcher sends it to my job.

**Comment by guichafy** [comment] 2018-03-29 22:40
@mniella Sorry to lengthen this discussion here, but when we are running in Kubernetes is there any file that configures the default parameters of a job launch?

**Comment by mminella** [comment] 2018-03-29 22:52
@guichafy There is a Gitter channel for Spring Cloud Data Flow where we can continue this conversation: https://gitter.im/spring-cloud/spring-cloud-dataflow

**Comment by cppwfs** [comment] 2018-03-30 01:07
When you jump on Gitter. Please answer the following:
1) How are you launching your tasks?  DataFlow or via the TaskLauncher Sink
2) What version of DataFlow and or TaskLauncher Sink are you using.
3) Can you share with us your definition?
