### ISSUE TITLE
Feature Request : Allow task/job datasource properties configuration

### ISSUE THREAD

**Issue by Tetradeus** [spring-cloud/spring-cloud-dataflow#3054] opened 2019-03-24 10:30 UTC
**Problem description:**
Tasks are launch with spring boot default datasource properties. 
When using scdf with several tasks/several databases/schema, it is a must to be able to 
use a secondary datasource for task infos.

**Solution description:**
Enable an easy solution to set a custom datasource config prefix :
scdf.datasource.url instead of spring.datasource.url
scdf.datasource.username instead of spring.datasource.username
...

**Description of alternatives:**
Overriding beans is difficult and usage of static method make it almost impossible...
TaskServiceUtils.updateTaskProperties(taskDefinition, this.dataSourceProperties);

**Comment by sabbyanandan** [comment] 2019-08-05 19:22
This appears to be a duplicate of https://github.com/spring-cloud/spring-cloud-dataflow/issues/3371 -- we will continue discussions here.

**Closed by sabbyanandan** 2019-08-05 19:22 UTC
Labels: duplicate
