### ISSUE TITLE
Support updating task launch on CF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#4267] opened 2020-11-30 16:28 UTC
Similar to [force-updating a stream](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#spring-cloud-dataflow-stream-lifecycle-force-update), it would be useful to also force-launch a task with _any_ version

**Comment by mminella** [comment] 2021-01-05 17:15
This will get complex (not arguing against it, just calling it out). For a CF launch, we recycle the droplet to prevent the need to recreate it with every launch. In order to accomplish this functionality on CF, we would need to explore one of two options:

1. Stop recycling the droplet and launch every time. This adds time to each launch (a non-trivial amount) as well as requires a more robust strategy around cleaning up old droplets which leads to the other option.
2. Track what execution is run with what droplet to allow recycling the correct droplet. This could result in one task definition resulting in multiple droplets deployed.

**Comment by dturanski** [comment] 2021-03-02 19:29
I cannot reproduce this with the `timestamp` sample with `SCDF 2.8.0-SNAPSHOT` deployed to our CF test environment. 
It appears to work as expected. 

Testing steps:
  - Deploy SCDF to CF
  - Register OOTB task apps
  - Register SNAPSHOT versions using https://dataflow.spring.io/Elston-BUILD-SNAPSHOT-task-applications-maven
  - Now I have 2 versions of timestamp
  - Create the timestamp task
  - Launch with default 2.1.1 version
  - Launch with SNAPSHOT version.  Droplet is deleted and replaced with the SNAPSHOT.  SCDF logs when it cleans up the downloaded artifact:
  ```Disk Space = 801292288 bytes, Total Disk Space = 1073741824 bytes
   2021-03-02T14:13:36.32-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:13:36.321  INFO 20 --- [-client-epoll-2] 
o.s.c.d.s.c.AbstractCloudFoundryDeployer : Successfully deleted the application resource: /home/vcap/.m2/repository/org/springframework/cloud/task/app/timestamp-task/2.1.2.BUILD-SNAPSHOT
```
- Launch with default version again.
```
 2021-03-02T14:24:16.30-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:24:16.305  INFO 20 --- [nio-8080-exec-3] o.s.c.d.s.c.AbstractCloudFoundryDeployer : Preparing to push an application from org.springframework.cloud.deployer.spi.cloudfoundry.CfEnvAwareResource@5aaa14c6. This may take some time if the artifact must be downloaded from a remote host.
   2021-03-02T14:25:03.15-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:25:03.157  INFO 20 --- [-client-epoll-2] o.s.c.d.s.c.CloudFoundryTaskLauncher     : Task timestamp launch successful
   2021-03-02T14:25:03.15-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:25:03.159  INFO 20 --- [-client-epoll-2] o.s.c.d.s.c.AbstractCloudFoundryDeployer : Free Disk Space = 826658816 bytes, Total Disk Space = 1073741824 bytes
   2021-03-02T14:25:03.16-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:25:03.160  INFO 20 --- [-client-epoll-2] o.s.c.d.s.c.AbstractCloudFoundryDeployer : Successfully deleted the application resource: /home/vcap/.m2/repository/org/springframework/cloud/task/app/timestamp-task/2.1.1.RELEASE
```
- Launch the same version - nothing downloaded
- Switch to SNAPSHOT:
```
   2021-03-02T14:26:35.76-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:26:35.766  INFO 20 --- [nio-8080-exec-4] o.s.c.d.s.c.AbstractCloudFoundryDeployer : Preparing to push an application from org.springframework.cloud.deployer.spi.cloudfoundry.CfEnvAwareResource@655db216. This may take some time if the artifact must be downloaded from a remote host.
   2021-03-02T14:27:26.53-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:27:26.534  INFO 20 --- [-client-epoll-2] o.s.c.d.s.c.CloudFoundryTaskLauncher     : Task timestamp launch successful
   2021-03-02T14:27:26.53-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:27:26.538  INFO 20 --- [-client-epoll-2] o.s.c.d.s.c.AbstractCloudFoundryDeployer : Free Disk Space = 801292288 bytes, Total Disk Space = 1073741824 bytes
   2021-03-02T14:27:26.54-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:27:26.545  INFO 20 --- [-client-epoll-2] o.s.c.d.s.c.AbstractCloudFoundryDeployer : Successfully deleted the application resource: /home/vcap/.m2/repository/org/springframework/cloud/task/app/timestamp-task/2.1.2.BUILD-SNAPSHOT
```
Do we have an example that fails?

**Comment by dturanski** [comment] 2021-03-02 19:31
I do see an error in the dataflow logs when switching versions. It appears to have no impact on this issue, but should be addressed. 

```
2021-03-02T14:26:31.91-0500 [APP/PROC/WEB/0] OUT 2021-03-02 19:26:31.917 ERROR 20 --- [nio-8080-exec-4] c.d.s.c.AbstractCloudFoundryTaskLauncher : Caught exception while querying for status of id=null
   2021-03-02T14:26:31.91-0500 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: taskId
   2021-03-02T14:26:31.91-0500 [APP/PROC/WEB/0] OUT 	at java.util.Objects.requireNonNull(Objects.java:228)
   2021-03-02T14:26:31.91-0500 [APP/PROC/WEB/0] OUT 	at org.cloudfoundry.client.v3.tasks.GetTaskRequest$Builder.taskId(GetTaskRequest.java:124)
   2021-03-02T14:26:31.91-0500 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.deployer.spi.cloudfoundry.AbstractCloudFoundryTaskLauncher.requestGetTask(AbstractCloudFoundryTaskLauncher.java:174)
...
```

**Comment by jvalkeal** [comment] 2021-03-11 16:20
I also poked around this and `t1:timestamp&&t2:timestamp` did run fine and update worked as well when I defined new versions(verified by checking which boot version it logs) and different `format` values.

I didn't see that exception mentioned above.

**Comment by dturanski** [comment] 2021-04-20 13:47
@jvalkeal @sabbyanandan can we close this?

**Comment by dturanski** [comment] 2021-05-17 14:08
Closing as invalid since we have verified that this works as designed.

**Closed by dturanski** 2021-05-17 14:08 UTC
Labels: for/blocker, status/need-feedback, type/enhancement
