### ISSUE TITLE
Generate docs from app-starter READMEs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow#473] opened 2016-03-28 14:39 UTC
As a developer, I'd like to generate SCStM and SCTM application docs from respective READMEs and aggregate them in the reference guide.

**Comment by ericbottard** [comment] 2016-04-13 11:16
Closing as a dupe of spring-cloud/spring-cloud-stream-app-starters#2

**Closed** 2016-04-13 11:16 UTC
Labels: documentation, duplicate, ready
