### ISSUE TITLE
Last app of a stream is labeled as sink app on deployment page but it is not a sink app.

### ISSUE THREAD

**Issue by berkaybayraktar** [spring-cloud/spring-cloud-dataflow#2453] opened 2018-09-28 08:36 UTC
### Version Information
Implementation Version: 1.6.3.RELEASE (spring-cloud-dataflow-server-local)
Core: 1.6.3.RELEASE (Spring Cloud Data Flow Core)
Dashboard: 1.6.1.RELEASE (Spring Cloud Dataflow UI)
Shell: 1.6.3.RELEASE (Spring Cloud Data Flow Shell)

**Note:** This bug also appears on 1.7.0.M1.

### Runtime Environment - App Deployer
Implementation Version:1.3.7.RELEASE
Name:LocalAppDeployer
Spi Version:1.3.3.RELEASE
Java Version:1.8.0_181
Platform Api Version:Linux 4.15.0-22-generic
Platform Client Version:4.15.0-22-generic
Platform Host Version:4.15.0-22-generic
Platform Type:Local
Spring Boot Version:1.5.14.RELEASE
Spring Version:4.3.18.RELEASE

### App Starters
 * The `http://bit.ly/Celsius-SR1-stream-applications-rabbitmq-10-maven` link used for bulk-app registration

### Problem Description

I created following streams.
```
STREAM1=file | transform > :destination
STREAM2=:destination > log
```
When I want to deploy `STREAM1`, the **transform** app is labeled as **sink** and the properties of that app are **uneditable**.

![image](https://user-images.githubusercontent.com/16611341/46196641-56ebff00-c310-11e8-8ea8-248e9b2f174c.png)

Also, to get properties of transform app, following request is made. However, as transform app is not a sink app, the request fails.

![image](https://user-images.githubusercontent.com/16611341/46196837-bc3ff000-c310-11e8-8b84-c2aa8e22e705.png)

```
Request URL: http://localhost:9393/apps/sink/transform
Request Method: GET
Status Code: 404 
```

**Comment by sabbyanandan** [comment] 2018-09-28 13:58
Thank you for the report. It appears to be a bug - we will look into it.

**Comment by ilayaperumalg** [comment] 2018-10-08 05:15
This is a bug from Spring Cloud Data Flow UI.

The issue is that when the named destination is used along with the `transformer` it is considered as `sink` by the Stream parser (both at the data flow core as well as the UI stream parser).

But, from the `stream deploy` page we try to fetch the properties of `transform` app using the `application type` returned by the stream parser. The UI needs to be fixed in this case to handle the appropriate type when the named destination is used.

Moving this to the data flow UI issue.

**Comment by ilayaperumalg** [comment] 2018-10-08 05:16
This issue was moved to spring-cloud/spring-cloud-dataflow-ui#931

**Closed by ilayaperumalg** 2018-10-08 05:16 UTC
Labels: bug 🐞, in progress
