### ISSUE TITLE
better error message when task name has wrong format

### ISSUE THREAD

**Issue by karthikbhat13** [spring-cloud/spring-cloud-dataflow#3443] opened 2019-08-17 19:58 UTC
When using scdf kubernetes server, we are required to give task name and cron expression for scheduling. Task name should only contain lower case letters/numbers according to regex on error message which is ^a-z0-9([a-z0-9]*[a-z0-9])?$ (Something like this, not sure). 

Issue is error message just shows a regex which is kinda misleading because one might think something is wrong with the cron expression. 

Can I change it better error message which mentions the field which is incorrect?
Thanks.

**Comment by sabbyanandan** [comment] 2019-08-19 14:56
@karthikbhat13: Thanks for re-opening the issue in the right repo. Just so that we are on the same page, can you share the task definition? Also, it'd help if you can share the versions in use, so we can attempt to reproduce, and improve the experience.

**Comment by cppwfs** [comment] 2019-08-19 21:09
For this given issue.   It needs to be open in the Kubernetes deployer.   Long story short K8's naming requirements for schedules is tighter than those of Cloud Foundry.  i.e. K8's can't accept uppercase characters no periods like CF.

**Comment by cppwfs** [comment] 2019-08-19 21:35
Here is a branch with the solution: https://github.com/cppwfs/spring-cloud-deployer-kubernetes/tree/SCDF-3443

**Comment by cppwfs** [comment] 2019-08-21 15:14
Moving this issue to spring-cloud-deployer-kubernetes because the error that is generated comes from the deployer's use of fabric8.   https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/320

**Closed by cppwfs** 2019-08-21 15:14 UTC
Labels: waiting-for-feedback
