### ISSUE TITLE
MQTT Source does not listen on defined topics

### ISSUE THREAD

**Issue by rjbgaspar** [spring-cloud/spring-cloud-dataflow#4460] opened 2021-03-30 09:35 UTC
**Description:**
In the dataflow server:

stream create --definition "mosquito-inbound: mqtt --client-id=scdfClient --qos=2 --username=admin --password=pwd --url='tcp://172.16.2.153:60065' --topics='in' | log" --name mqtt-in --deploy

Stream is deployed successfully

Instance mqtt-in.mosquito-inbound logs
```
2021-03-26 16:06:55.108  INFO [mqtt-source,,,] 2543 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version: 2.5.1
2021-03-26 16:06:55.109  INFO [mqtt-source,,,] 2543 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: 0efa8fb0f4c73d92
2021-03-26 16:06:55.109  INFO [mqtt-source,,,] 2543 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1616774815108
2021-03-26 16:06:55.142  INFO [mqtt-source,,,] 2543 --- [ad | producer-1] org.apache.kafka.clients.Metadata        : [Producer clientId=producer-1] Cluster ID: lWzPoXipThSg2Mo-CDBnZA
2021-03-26 16:06:55.170  INFO [mqtt-source,,,] 2543 --- [           main] o.a.k.clients.producer.KafkaProducer     : [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 30000 ms.
2021-03-26 16:06:55.214  INFO [mqtt-source,,,] 2543 --- [           main] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'output' has 1 subscriber(s).
2021-03-26 16:06:55.616  INFO [mqtt-source,,,] 2543 --- [           main] .m.i.MqttPahoMessageDrivenChannelAdapter : started bean 'mqttInbound'; defined in: 'org.springframework.cloud.fn.supplier.mqtt.MqttSupplierConfiguration'; from source: 'org.springframework.core.type.StandardMethodMetadata@264f218'
2021-03-26 16:06:55.745  INFO [mqtt-source,,,] 2543 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 20086 (http) with context path ''
2021-03-26 16:06:55.832  INFO [mqtt-source,,,] 2543 --- [           main] s.c.s.a.m.s.k.MqttSourceKafkaApplication : Started MqttSourceKafkaApplication in 25.864 seconds (JVM running for 28.109)
```

Client connected successfully.
Instances for app mqtt-in.log logs

```
2021-03-26 16:07:05.412  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: 0efa8fb0f4c73d92
2021-03-26 16:07:05.412  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1616774825412
2021-03-26 16:07:05.418  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] org.apache.kafka.clients.Metadata        : [Consumer clientId=consumer-mqtt-in-3, groupId=mqtt-in] Cluster ID: lWzPoXipThSg2Mo-CDBnZA
2021-03-26 16:07:05.437  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-mqtt-in-3, groupId=mqtt-in] Discovered group coordinator kafka-broker:9092 (id: 2147482646 rack: null)
2021-03-26 16:07:05.441  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-mqtt-in-3, groupId=mqtt-in] Found no committed offset for partition mqtt-in.mosquito-inbound-0
2021-03-26 16:08:05.443  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-mqtt-in-3, groupId=mqtt-in] Found no committed offset for partition mqtt-in.mosquito-inbound-0
2021-03-26 16:09:05.446  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-mqtt-in-3, groupId=mqtt-in] Found no committed offset for partition mqtt-in.mosquito-inbound-0
2021-03-26 16:10:05.446  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-mqtt-in-3, groupId=mqtt-in] Found no committed offset for partition mqtt-in.mosquito-inbound-0
2021-03-26 16:11:05.449  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-mqtt-in-3, groupId=mqtt-in] Found no committed offset for partition mqtt-in.mosquito-inbound-0
2021-03-26 16:12:05.452  INFO [log-sink,,,] 2546 --- [pool-1-thread-1] o.a.k.c.c.internals.ConsumerCoordinator  : [Consumer clientId=consumer-mqtt-in-3, groupId=mqtt-in] Found no committed offset for partition mqtt-in.mosquito-inbound-0
```

I publish into "in" topic and nothing happens, also tried to /in the same thing.

**Release versions:**
Versions provided in DATAFLOW_VERSION="2.7.1" and using SKIPPER_VERSION="2.6.1".
Eclipse Mosquitto version 2.0.9

**Additional context:**
I am following the instructions in [Installing by Using Docker Compose](https://dataflow.spring.io/docs/installation/local/docker/) in local machine from the documentation.
I also tried with the mqtt sync and it works, I received the message.

**Comment by sabbyanandan** [comment] 2021-04-05 20:59
Thanks for reporting, @rjbgaspar, but it seems like a duplicate of https://github.com/spring-cloud-stream-app-starters/mqtt/issues/18 and https://github.com/spring-cloud/stream-applications/issues/160.

**Closed by sabbyanandan** 2021-04-05 20:59 UTC
Labels: status/need-triage
