### ISSUE TITLE
Restarting batch-jobs re-adds datasource properties 

### ISSUE THREAD

**Issue by praveenpotru** [spring-cloud/spring-cloud-dataflow#1800] opened 2017-11-21 09:00 UTC
### Environment:
Spring cloud data flow local -1.2.3.RELEASE
Spring Boot - 1.5.4.RELEASE
Spring Batch – 3.0.7.RELEASE
DB - H2-1.4  

### Following exception is thrown on restart of a Stopped/Failed job from cloud dataflow UI ,

java.sql.SQLException: Unable to load class: org.h2.Driver,org.h2.Driver from ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@5b2133b1;ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@5b2133b1
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:283)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:735)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:667)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:482)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:326)
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:366)
	at org.springframework.batch.support.DatabaseType.fromMetaData(DatabaseType.java:97)
	at org.springframework.cloud.task.repository.support.TaskExecutionDaoFactoryBean.buildTaskExecutionDao(TaskExecutionDaoFactoryBean.java:116)
Caused by: java.lang.ClassNotFoundException: Unable to load class: org.h2.Driver,org.h2.Driver from ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@5b2133b1;ClassLoader:org.springframework.boot.loader.LaunchedURLClassLoader@5b2133b1
	at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:56)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:271)
	... 130 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.h2.Driver,org.h2.Driver
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:38)
	... 131 common frames omitted

### Reason is, dataflow local server is sending data source & all other config properties twice on restart of a job

 2017-11-21 13:59:01 [main] INFO  c.v.t.m.MigrationApplication - provided arguments "--endpoints.jmx.unique-names=true --endpoints.shutdown.enabled=true --spring.datasource.username=sa --ex-migration.task-job-name=migrateExample --spring.datasource.url=jdbc:h2:tcp://localhost/~/cldbtest --spring.datasource.driverClassName=org.h2.Driver --server.port=35938 --spring.cloud.task.name=migrateExample --spring.jmx.default-domain=migrateExample-a96542ac-e71f-4cb3-8e77-feb9ae678c02 --endpoints.jmx.unique-names=true --endpoints.shutdown.enabled=true --spring.datasource.username=sa --ex-migration.task-job-name=migrateExample --spring.datasource.url=jdbc:h2:tcp://localhost/~/cldbtest --spring.datasource.driverClassName=org.h2.Driver --server.port=24599 --spring.cloud.task.name=migrateExample --job.skipIncrement=deserd --spring.jmx.default-domain=migrateExample-6d26afc0-318e-444a-9608-20ed634d8952 --spring.cloud.task.executionid=461"

Above is the application log of arguments  from cloud dataflow, all  properties are passed twice. As *--spring.datasource.driverClassName* is appearing twice, value is concatenated and becoming as org.h2.Driver,org.h2.Driver. And then a ClassNotFound exception is being thrown on startup od application which is obvious.

#### By the way Spring boot concatenates values if same argument passed twice from command line? or its bug from boot side?

**Comment by cppwfs** [comment] 2017-11-21 15:20
I was able to reproduce this issue, using the following steps:
1) Launch a Batch Job that will fail
2) Relaunch the job via the UI
When relaunching the job from the shell this does not occur.  ie. launch the task with the same parameters.  
This is because the restartJobExecution in the DefaultTaskJobService sends the same parameters that were originally sent with the first execution.  Then dataflow applies its datasource properties again.

**Comment by mminella** [comment] 2017-11-21 15:29
Why do these not go through the same REST call?

**Comment by cppwfs** [comment] 2017-11-21 15:36
In my case above the shell does not have a restart command.  I could have used the restart from curl.  But in this case I was just in diagnosis mode, and wanted launch it again using basic Batch behavior.

**Comment by mminella** [comment] 2017-11-21 15:43
So are we saying that the UI and Shell do the same thing just using different paths or that you did something different?  What I'm getting at is that the UI and shell should be using the same REST API for each piece of functionality.  If that isn't the case, it should be fixed to be consistent as well as addressing this issue.

**Comment by cppwfs** [comment] 2017-11-21 15:50
Point taken.  I think the answer is that the shell does not have a `job restart --jobInstanceId=123` command.  We need to add this story .

**Comment by sabbyanandan** [comment] 2017-12-19 18:15
Update: Once the batch-job is launched, the datasource properties are already stored for the job-execution. Upon "restart" (_you can from the UI; no option exist in the shell_), we are re-adding the datasource properties and it should not.

**Comment by cppwfs** [comment] 2018-02-28 18:47
Retested using the Spring Cloud Data Flow 4.x with the following batch job https://github.com/cppwfs/multistep.   And was unable to reproduce the problem.
1) Put a exception in a step in multistep test app
2) Build multistep
3) register it with Data Flow
4) create task definition
5) launch task definition
6) remove exception from step
7) build multistep
8) rerun the task definition using the UI Restart button on the Job tab.

**Closed by cppwfs** 2018-02-28 18:47 UTC
Labels: batch-job/task, bug, in progress

**Comment by siddhantsorann** [comment] 2018-10-26 10:35
This issue is also there in the 1.7.0.RELEASE Kubernetes server.

**Comment by I333750** [comment] 2018-12-12 10:33
Still get this error with <spring.cloud.task.version>2.0.0.RELEASE</spring.cloud.task.version>. Its okay for me launch in local, but in the server then it will fail

**Comment by trlo-bite** [comment] 2019-07-24 12:08
I get the same problem in 2.1.2.RELEASE using Kubernetes. Steps to reproduce using Spring's timestamp-batch app:

1. Register app with URI docker:springcloudtask/timestamp-batch-task:2.1.0.RELEASE
2. Create task
3. Launch task (both jobs should complete)
4. Change job status to FAILED in database so it could be restarted
5. Restart using UI

Exception:
```
Caused by: java.lang.IllegalStateException: Cannot load driver class: org.mariadb.jdbc.Driver,org.mariadb.jdbc.Driver
	at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:224) ~[spring-boot-autoconfigure-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.initializeDataSourceBuilder(DataSourceProperties.java:176) ~[spring-boot-autoconfigure-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:44) ~[spring-boot-autoconfigure-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari.dataSource(DataSourceConfiguration.java:88) ~[spring-boot-autoconfigure-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari$$EnhancerBySpringCGLIB$$8b2cd773.CGLIB$dataSource$0(<generated>) ~[spring-boot-autoconfigure-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari$$EnhancerBySpringCGLIB$$8b2cd773$$FastClassBySpringCGLIB$$b4e77fbb.invoke(<generated>) ~[spring-boot-autoconfigure-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari$$EnhancerBySpringCGLIB$$8b2cd773.dataSource(<generated>) ~[spring-boot-autoconfigure-2.1.5.RELEASE.jar!/:2.1.5.RELEASE]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.7.RELEASE.jar!/:5.1.7.RELEASE]
	... 63 common frames omitted
```

**Comment by sabbyanandan** [comment] 2019-07-24 14:05
@trlo-bite / @I333750: Please avoid commenting on closed issues going forward; unless we specifically look for it (like how I did), we won't have visibility into comments on closed issues. If this is a reproducible case, feel free to open a separate issue with steps detailing as to how to replicate it, and we can have a look.
