### ISSUE TITLE
default spring repo at local scdf is not available 

### ISSUE THREAD

**Issue by borg1310** [spring-cloud/spring-cloud-dataflow#5321] opened 2023-04-28 08:34 UTC
hi,

the default maven repo ([springRepo](https://docs.spring.io/spring-cloud-dataflow/docs/1.2.3.RELEASE/reference/html/howto.html)) in a local scdf installation is not available since yesterday:
https://repo.spring.io/libs-snapshot

- is that intended?
- maybe the url has changed: https://repo.spring.io/libs-snapshot-local or https://repo.spring.io/ui/native/libs-snapshot-local
- where i can change the default url of the springRepo?

thanks in advance
best regards,
juergen

**Comment by ck-trigfb** [comment] 2023-04-28 11:07
Hi,

same problem here. In skipper log i get 401 (permission denied) error on https://repo.spring.io/libs-snapshot
`Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.springframework.cloud.stream.app:file-source-kafka:jar:3.2.1 from/to springRepo (https://repo.spring.io/libs-snapshot): status code: 401, reason phrase:  (401)
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.cloud.stream.app:file-source-kafka:jar:3.2.1 from/to springRepo (https://repo.spring.io/libs-snapshot): status code: 401, reason phrase:  (401)`

Yesterday morning i had version 2.9.1 up and running. In the evening it started getting 401 error. I also tried version 2.10.2 but got the same error.

Regards,
Christoph

**Comment by onobc** [comment] 2023-04-28 17:59
Thanks for the report. This is due to https://status.spring.io/incidents/95cyglctjbs4?u=zzj95h0528qh .
You can subscribe to the incident in the above link. We are looking for a workaround for this issue now and will reply here w/ results (good or bad) asap.

**Comment by onobc** [comment] 2023-04-28 18:11
The brownout will actually be removed in ~50m (4/28 @ 12pm PST) so I will not look for a workaround. 

Thanks for your patience.

**Comment by onobc** [comment] 2023-05-01 15:54
We are going to configure in `repo.spring.io/snapshot` + `maven central` which should solve this issue once the access is removed from `libs-snapshot`.

**Comment by onobc** [comment] 2023-05-03 20:38
Closed via https://github.com/spring-cloud/spring-cloud-dataflow/commit/83b530d450bea2491f1f34c45e814ba97797134b

**Closed by onobc** 2023-05-03 20:38 UTC
Labels: status/in-progress
