### ISSUE TITLE
Dataflow Tasks are not working with Spring Batch

### ISSUE THREAD

**Issue by magx2** [spring-cloud/spring-cloud-dataflow#1822] opened 2017-12-01 09:53 UTC
I'm having Spring Batch ```job``` that is also dataflow ```task```. When I run this job everything seems OK, In ```Tasks``` > ```Executions``` I can see that tasks finished successfully. On the other hand when I go to ```Jobs``` tabs I'm getting this error (in command line):

    java.lang.NullPointerException: null
        at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService.getTaskJobExecution(DefaultTaskJobService.java:240) ~[spring-cloud-dataflow-server-core-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService.getTaskJobExecutionsForList(DefaultTaskJobService.java:233) ~[spring-cloud-dataflow-server-core-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.dataflow.server.service.impl.DefaultTaskJobService.listJobExecutions(DefaultTaskJobService.java:103) ~[spring-cloud-dataflow-server-core-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at org.springframework.cloud.dataflow.server.controller.JobExecutionController.list(JobExecutionController.java:91) ~[spring-cloud-dataflow-server-core-1.2.2.RELEASE.jar!/:1.2.2.RELEASE]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]

Spring Dataflow version = ```1.2.2```

**Comment by mminella** [comment] 2017-12-01 11:55
This is the same issue as [here](https://stackoverflow.com/questions/47570735/dataflow-tasks-are-not-working-with-spring-batch), correct?

**Comment by magx2** [comment] 2017-12-01 12:13
Yes, this was also posted by me.

**Comment by magx2** [comment] 2017-12-05 12:53
Any update in this?

**Comment by cppwfs** [comment] 2017-12-06 02:02
I was able to recreate this problem by executing a Spring Batch (boot) application that used the batch tables being used by SCDF.  The Batch app did not have the @EnableTask annotation applied to the configuration (or application).  i.e. DataFlow has an expectation that all Batch Apps that use its Batch tables are also a Spring Cloud Task.  In this case we probably need to make DataFlow resilient enough to handle a case where a Batch Application is not a task.

**Comment by magx2** [comment] 2017-12-06 22:44
Hmm that weird. All my batch jobs are also cloud task so this is not case that you are decribing

**Comment by cppwfs** [comment] 2017-12-09 18:20
I have an additional question.  Did any of your tasks executions fail? i.e. return return a value other than 1 or do not show a end-time?     I have found the root cause to the issue I enumerated above, but still trying to discover the root cause of what you are reporting.

**Comment by magx2** [comment] 2017-12-09 22:20
Yep, I had jobs that ended with status code != 0, also there was some jobs with end time equals N/A

**Comment by sabbyanandan** [comment] 2017-12-11 01:22
@cppwfs: A quick follow-up to your [comment](https://github.com/spring-cloud/spring-cloud-dataflow/issues/1822#issuecomment-349506077). SCDF orchestrates either SCSt or SCT applications and the standalone batch-job as a Boot app is out of scope for SCDF right now.

**Comment by magx2** [comment] 2017-12-11 20:06
@sabbyanandan I just want to say that Spring Batch Admin is getting deprecated suggested replacement for it is SCDF, so it would be nice if everything regarding batch jobs would work

**Comment by mminella** [comment] 2017-12-13 18:21
@magx2 Per the documentation at the bottom of the Spring Batch Admin migration guide (https://github.com/spring-projects/spring-batch-admin/blob/master/MIGRATION.md), we do require that batch jobs be made into tasks by adding that single annotation.  Since Spring Batch jobs need to be repackaged to migrate, we felt it's a minor change.  Is there some reason that isn't an option?

**Comment by cppwfs** [comment] 2017-12-13 18:25
Let me clarify a point on this issue.  @magx2 said that all his batch jobs were tasks.   While I was able to identify the code that is failing in SCDF, I was unable to reproduce the root cause (i.e. a Task -batch job that did not add an entry in the TASK_BATCH table).   @magx2 Can you provide an example that consistently causes your issue.

**Comment by magx2** [comment] 2017-12-13 22:45
@mminella SCDF is a great idea! I also think that having separate spring boot jars with jobs will be better than having on big jar with all jobs. Also annotation ```@EnableTask``` is great. What I tried to say before is that everything should work for spring batch, especially Job tab in SCDF.

@cppwfs Hmm.. I will try to do this tomorrow... I just wonder what will happen if my task will run ```#enableTask``` annotation but not be able to run batch job? I think it might be this case

**Comment by cppwfs** [comment] 2017-12-13 23:29
We have tested @EnableTask with batch applications and there are several features that task offers for batch applications.   With that being said, reiterating what Michael said earlier, if you want to use DataFlow to view Job Executions or orchestrate Jobs, the Batch apps are required to have @EnableTask.

**Comment by magx2** [comment] 2017-12-14 07:40
I'm using ```@EnableTask``` with my Spring Batch Jobs, the problem is that I'm getting error on Jobs tab

**Comment by cppwfs** [comment] 2017-12-14 13:39
Based on my investigation, the error you are seeing is that there is a missing entry or entries in the TASK_BATCH (TASK_TASK_BATCH) table.  Meaning there is a `Job_Execution_ID` in the BATCH_JOB_EXECUTION table that does not have a corresponding entry in the TASK_TASK_BATCH table i.e. there is no `Task_Execution_ID` for the `Job_Execution_Id`.  SCDF is throwing an exception because it is trying to map a JobExecution to a TaskExecution and is failing because that map is missing.  The work around is to remove the Job Executions that don't have an associated Task Execution.
Because the vagueness of the exception, this was the only scenario, that I could see that would cause this problem.        And thus the questions, "Are you running batch job boot applications that do not include the `@EnableTask` ?"   The primary question I have is if you are including `@EnableTask` with all your Batch boot applications, how can this error occur, and at this time I have been unable to reproduce this scenario.   And thus my request for a reproducible case.

**Comment by magx2** [comment] 2017-12-14 14:34
OK I will try to reproduce this at home.

I have 2 things that are done differently than normal :

1.  I have enable task annotation on parent project (but everything is being loaded)
2. I'm using 2.0.0.M2 version. May it be problem?

**Comment by sabbyanandan** [comment] 2017-12-14 14:42
We are continuing to go back and forth on this; let's just have your reproducible project - we can review then.

**Comment by lframirez89** [comment] 2017-12-15 03:43
Hi all,

As I posted here: https://stackoverflow.com/questions/47570735/dataflow-tasks-are-not-working-with-spring-batch/47825418#47825418

The reason for the null pointer exception is exactly as cppwfs described, because there is a missing record in the TASK_TASK_BATCH table. For me the root cause was because I had substituted the spring-cloud-starter-task dependency for the spring-cloud-task-core dependency thinking it was all I needed, (also seeing that it compiled successfully and the task ran just fine). However this change was what stopped the record from being written to the TASK_TASK_BATCH table. As soon as I replaced spring-cloud-task-core back to spring-cloud-starter-task, the records started to be written again. After checking what spring-cloud-starter-task included, I noticed that it doesn't just contain spring-cloud-task-core, but also **spring-cloud-task-batch** and spring-cloud-task-stream, the first of which is what inserts those records into the TASK_TASK_BATCH table.

**Comment by nishkarma** [comment] 2017-12-15 04:47
For me, this happened the job name or step name are duplicated.
We are doing a project with several persons.
One member copied the module, but he does not changed the job, step name.
After review the job log in logback log file, found the job, step name are duplicated.
When he modified the names, Dashboard>Jobs displayed the job execution list.

**Comment by magx2** [comment] 2017-12-15 11:28
Here is gh repo where I reproduced this error https://github.com/magx2/dataflow-error

FYI I'm doing _ETL_ with help of Spring Batch. I have 2 data source: ```in``` and ```out```. SCDF is working on ```out``` DB.

**Comment by mminella** [comment] 2017-12-15 15:40
@magx2 If you read the comments made by @iframirez89 you'll see that it didn't work for him with the `spring-cloud-task-core` as the only dependency...you need to use the starter.  Your Github repo is not using the starter.  Can you try with it?

**Comment by lframirez89** [comment] 2017-12-15 16:09
@magx2 Also, before you substitute the spring-cloud-task-core back to the spring-cloud-starter-task, make sure to fix your TASK_TASK_BATCH table first, by adding the missing records manually for whichever tasks you ran that didn't get recorded in this table (by looking at the id's on the BATCH_JOB_EXECUTION and TASK_EXECUTION tables). Otherwise you could do what I did which was to reset my batch/task repos (by deleting all the data in the batch/task tables and resetting the sequences). I did this because I had previously messed with the other tables manually and I left some inconsistencies, so I preferred starting again with a clean repo... As soon as the missing records get added, you should stop getting the NullPointerException when going to the Dashboard > Jobs tab. After that you can add the spring-cloud-starter-task dependency and run a job, and you will see that the new record will be written to the TASK_TASK_BATCH table as expected. Then the data should remain consistent.

**Comment by magx2** [comment] 2017-12-15 21:08
I've changed

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-task-core</artifactId>
			<version>2.0.0.M2</version>
		</dependency>

to

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-task</artifactId>
		</dependency>

And now maven cannot find this annotation: ```org.springframework.cloud.task.configuration.EnableTask```. Am I missing smthing?

**Comment by cppwfs** [comment] 2018-01-09 14:10
@mag2x Were you able to get this to work?

**Comment by magx2** [comment] 2018-01-14 13:44
Nope I'm still getting compilation error

**Closed** 2018-03-01 17:11 UTC
Labels: backport-1.3.x, batch-job/task, bug, in pr
