### ISSUE TITLE
The task configured as boot2 application cannot be executed in `SCDF 2.11.0 RC1`.

### ISSUE THREAD

**Issue by 21kyu** [spring-cloud/spring-cloud-dataflow#5459] opened 2023-09-07 08:37 UTC
**Description:**
application: Spring Batch 4
task: Consists of a single application
dataflow: 2.11.0-RC1
env: k8s

When I try to run a task, the following error pop-up occurs.

`PreparedStatementCallback; SQL [INSERT INTO BOOT3_TASK_EXECUTION_METADATA (ID, TASK_EXECUTION_ID, TASK_EXECUTION_MANIFEST) VALUES (?, ?, ?)]; ERROR: insert or update on table "boot3_task_execution_metadata" violates foreign key constraint "boot3_task_metadata_fk" Detail: Key (task_execution_id)=(66) is not present in table "boot3_task_execution".; nested exception is org.postgresql.util.PSQLException: ERROR: insert or update on table "boot3_task_execution_metadata" violates foreign key constraint "boot3_task_metadata_fk" Detail: Key (task_execution_id)=(66) is not present in table "boot3_task_execution".`

Is this a bug? or did I miss some setting?

**Release versions:**
2.11.0-RC1

**Comment by cppwfs** [comment] 2023-09-07 19:58
Can you share with us the steps that you took to register the Boot 2 application with spring cloud dataflow.   
Thank you

**Comment by corneil** [comment] 2023-09-08 11:16
Executed `<timestamp || timestamp-batch> && <timestamp3 || timestamp-batch3>` with PostgreSQL.

**Comment by 21kyu** [comment] 2023-09-11 00:47
> Can you share with us the steps that you took to register the Boot 2 application with spring cloud dataflow? Thank you

Hello @cppwfs, thank you for reply first.

I registered the boot 2 application through the following proccess.

1. click the `ADD APPLICATION(S)` button in the Applications.
2. click `Register one or more applications` and enter the name, type(task), boot version(2.x) and uri(container image uri created with spring batch 4.0 in aws ecr).
3. click `IMPORT APPLICATION(S)` button to complete the registration.

**Comment by 21kyu** [comment] 2023-09-11 00:57
After several registrations and deletions, we confirmed that the container was running with the correct arguments.

```
    --spring.cloud.deployer.bootVersion=2
    --spring.cloud.task.schemaTarget=boot2
    --spring.batch.jdbc.table-prefix=BATCH_ 
    --spring.cloud.task.tablePrefix=TASK_
```

**Comment by cppwfs** [comment] 2023-09-11 11:15
When you created the application did you include the Spring Cloud Task as a dependency and add the @EnableTask annotations?

**Comment by onobc** [comment] 2023-09-11 18:14
Hi @21kyu ,

So did the issue go away? Or are you still seeing problems? 

Thanks

**Comment by 21kyu** [comment] 2023-09-12 02:28
> When you created the application did you include the Spring Cloud Task as a dependency and add the @EnableTask annotations?

Yes, that's right, all spring batch applications used in scdf have the @enableTask annotation added.

**Comment by 21kyu** [comment] 2023-09-12 02:30
Hi @onobc ,

Yes, it's working fine for now. Can I close the issue?

Thank you.

**Comment by onobc** [comment] 2023-09-12 04:00
Thanks for confirming @21kyu , 
We want to take another look tomorrow at our team meeting tomorrow and we will probably close it then.

**Comment by onobc** [comment] 2023-09-13 15:34
Closing as cannot reproduce.

**Closed by onobc** 2023-09-13 15:34 UTC
Labels: status/need-feedback
