### ISSUE TITLE
NullPointerException  when accessing the  Jobs tabs

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#2076] opened 2018-03-01 11:45 UTC
Hello
I'm getting the NPE when accessing the  Jobs tab in dashboard after launching the CTR with  `buggy` task  that  can't be started due to `BeanCreationException` ,see  releated issue [here ](https://github.com/spring-cloud/spring-cloud-task/issues/398)

````
2018-03-01T13:35:27.52+0200 [RTR/0] OUT
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.cloud.dataflow.server.controller.JobExecutionController.list(JobExecutionController.java:91) ~[spring-cloud-dataflow-server-core-1.3.0.RELEASE.jar!/:1.3.0.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.13.RELEASE.jar!/:4.3.13.RELEASE]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar!/:8.5.23]
   2018-03-01T13:35:27.25+0200 [APP/PROC/WEB/0] OUT     at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.9.RELEASE.jar!/:1.5.9.RELEASE]
````

**Comment by sabbyanandan** [comment] 2018-03-01 14:33
When creating new issues, it'd be good to have more details. See [wiki](https://github.com/spring-cloud/spring-cloud-dataflow#reporting-issues). Specifically, the versions are important. 

We will have to handle the exceptions more gracefully, though.

**Comment by mminella** [comment] 2018-03-01 15:14
This is a duplicate of https://github.com/spring-cloud/spring-cloud-dataflow/issues/1822.

**Closed by mminella** 2018-03-01 15:14 UTC
Labels: bug, ready
