### ISSUE TITLE
ExecutionContext is not deserialized by the REST Client API

### ISSUE THREAD

**Issue by svesch84** [spring-cloud/spring-cloud-dataflow#2992] opened 2019-03-07 11:26 UTC
**Description:**
When I use the method stepExecutionProgress of the org.springframework.cloud.dataflow.rest.client.JobOperations class the returned StepExecution object does not have any ExecutionContext entry, even if the stored step execution object on the dataflow server has one. 
When I query the REST endpoint http://localhost:9393/jobs/executions/5/steps/7 manually the JSON documents shows the correct execution context (see attached). 

**Release versions:**
1.7.3, 1.7.4, 2.0.0

**Custom apps:**
I wrote a JUnit test to reproduce the problem, not sure if the jackson object mapper uses all correct mixin. Nevermind the behaviour seems to be the same. The de-serialized execution context is empty. 
My unit test can be found at: 
https://github.com/svesch84/execution-context-rest-api

**Comment by sabbyanandan** [comment] 2019-03-08 15:09
@svesch84: Thanks for reporting. We will have a look.

**Comment by ghillert** [comment] 2019-03-11 08:51
Hi @svesch84 -

Have you looked at the sample at https://github.com/spring-cloud/spring-cloud-dataflow-samples/blob/master/dataflow-template-example/pom.xml ?

You should be able to retrieve the relevant data using:

```java
    	RestTemplate restTemplate = DataFlowTemplate.getDefaultDataflowRestTemplate();
    	DataFlowTemplate dataFlowTemplate = new DataFlowTemplate(
    		    new URI("http://localhost:9393/"), restTemplate);
    	StepExecutionProgressInfoResource a = dataFlowTemplate.jobOperations().stepExecutionProgress(1l, 1l);
```

The Spring Cloud Data Flow Shell, is using the very same infrastructure.

**Comment by jvalkeal** [comment] 2019-03-11 14:55
Stories of configuring `RestTemplate` for scdf or in scdf is still a bit incomplete but I think you are missing `HAL` related setup(registering module Jackson2HalModule). i.e. shell configures `RestTemplate` using this:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/9c46ae10897684ff66b3752730974fc644406051/spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/DataFlowTemplate.java#L242-L256

UI is doing its own parsing as it's in angular/ts/js world.

**Comment by svesch84** [comment] 2019-03-11 14:59
The example  https://github.com/spring-cloud/spring-cloud-dataflow-samples/blob/master/dataflow-template-example/pom.xml is using _DataFlowTemplate.getDefaultDataflowRestTemplate_() which uses the _prepareRestTemplate_ method to create the _RestTemplate_. 
So I'm quite sure that the HAL module is correctly registered and even the jackson mixins are registered in that method.

**Comment by svesch84** [comment] 2019-03-11 15:12
BTW.: does the data flow shell even offer the functionality to read the step execution context? As far as I have seen the shell only supports to display details of the step execution, but does not show the data of the execution context.

**Comment by ghillert** [comment] 2019-03-12 10:17
@svesch84 I can confirm the issue, finally. However, I will need a few more hours to provide a fix later today. It is per se not a bug but in fact insufficient support for the execution context. The main issue is that the `ExecutionContext` object (Part of Spring Batch) is not very serialization-friendly. As such, we did a short-cut when we added initial support 2 years ago and provided 2 serializers/deserializers - one for the server-side and one for the client-side to (insufficiently) work around the issue (basically omitting to deserialize the `ExecutionContext`)

The solution is to implement a dedicated `JsonDeserializer` for the `ExecutionContext` and ensure the same configuration for the Rest Client as well as the server-side plus a few test-cases to ensure nothing breaks.

You are right in regards to the Shell support: I have created a separate issue for that:

https://github.com/spring-cloud/spring-cloud-dataflow/issues/3007

**Comment by svesch84** [comment] 2019-03-12 18:26
Sounds great, many thanks. 
For my purpose I found a workaround to deserialize the JSON manually in my client code. So no hurry in that.

**Comment by ghillert** [comment] 2019-03-14 10:04
@svesch84 I submitted a PR that hopefully unifies the relevant mixins and solves the issue between server and rest client.

**Comment by sabbyanandan** [comment] 2019-03-20 15:41
Addressed in https://github.com/spring-cloud/spring-cloud-dataflow/commit/a62989bee361e9486d82c066163177af4b9b1549.

**Closed by sabbyanandan** 2019-03-20 15:41 UTC
Labels: in pr
