### ISSUE TITLE
Docker Compose installation does not support docker image resources.

### ISSUE THREAD

**Issue by derrick-anderson** [spring-cloud/spring-cloud-dataflow#3643] opened 2019-11-20 02:56 UTC
**Description:**
The Current (`2.2.1`) version of Spring Cloud Data Flow's  Docker-Compose based installation does not support utilizing docker applications.

**Release versions:**
`DATAFLOW_VERSION=2.2.1.RELEASE`
`SKIPPER_VERSION=2.1.2.RELEASE`

**Steps to reproduce:**
1 .) Download the docker compose file located [here](https://raw.githubusercontent.com/spring-cloud/spring-cloud-dataflow/v2.2.1.RELEASE/spring-cloud-dataflow-server/docker-compose.yml)
2. ) Update the docker compose file `dataflow-import` section as below to import the docker apps instead of maven. 
```  app-import:
    image: springcloud/openjdk:2.0.0.RELEASE
    container_name: dataflow-app-import
    depends_on:
      - dataflow-server
    command: >
      /bin/sh -c "
        ./wait-for-it.sh -t 180 dataflow-server:9393;
EDIT THIS LINE BELOW
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=https://dataflow.spring.io/kafka-docker-latest&force=true';
        echo 'Stream apps imported'
        wget -qO- 'http://dataflow-server:9393/apps' --post-data='uri=https://dataflow.spring.io/task-maven-latest&force=true';
        echo 'Task apps imported'"
```
3. ) Define the following stream:
```time | log```

4. ) Attempt to deploy the above stream with a `server.port` property of 8081/8082 for the two servers

5. ) Observe the failure of deployment and review skipper logs for the below statement 
```
... Caused by: java.io.IOException: error=2, No such file or directory....
...Caused by: java.io.IOException: Cannot run program "docker" (in directory "/tmp/spring-cloud-deploye...
```

**Screenshots:**
Where applicable, add screenshots to help explain your problem.

**Additional context:**
I was unable to find any documentation or reasonable explanation as to why docker does not ship with the skipper server by default.

**Comment by sabbyanandan** [comment] 2019-11-20 20:24
Hi, @derrick-solstice. I believe there's a support to deploy Docker apps in Local deployer, which SCDF on Local/Docker-Compose model should be using it anyway. Have you tried deploying docker apps outside of the Docker Compose model?

Maybe there's a bug lurking around here, we will have a look, as well.

One other thing. If you're in Local, you will be producing Maven artifacts from the local builds, and the local `.m2`/maven cache should have the uber-jar anyway. So, I'm curious why you'd want to specifically deploy as Docker images as opposed to Maven artifacts.

**Comment by derrick-solstice** [comment] 2019-11-22 15:41
@sabbyanandan @tzolov 

I was working with Docker Images to deploy to SCDF In GKE (as a continuation of my previous work) and was wanting to continue to work with docker images to ensure a consistent workflow when running local vs in the cloud.  In this scenario, i was developing GraalVM images wrapped in a docker container to deploy to K8s and didn't want to incur the cost of spinning up a GKE cluster just to test.  Hence the local deployment.  

It's a fair statement that it's not that common, but there's also not any logical reason not to include Docker in the skipper server build for local.  If this falls into the 'wont fix' bucket just let me know.

-Thanks for the time

**Comment by sabbyanandan** [comment] 2019-11-22 15:46
Thanks for the background. That helps. Also, when you get a chance, can you start SCDF and Skipper manually (i.e. `java -jar ..`), and try the same Docker images? Just curious if it is a Docker Composed only thing.

We will review it on our end, too. The foundational bits exist in the Local-deployer; we will have to find out if it is failing to translate.

**Comment by derrick-solstice** [comment] 2019-11-22 19:04
Sabby,

I will follow the instructions for local manual installation to start up the Skipper and Dataflow servers over the weekend.  Thanks for getting back to me.

**Comment by tzolov** [comment] 2019-11-25 11:25
@derrick-solstice, While the `LocalAppDeployer` (used internally by the DataFlow and Skipper engines) supports docker apps deployment it was designed to support the manual SCDF/Skipper installation. When used with `docker-compose` installation it ends-up into trying to run `Docker in Docker` which is not supported. 
Because the DataFlow and Skipper engines already run in docker containers (the docker-compose starts both in docker containers), when they use the local deployer to deploy apps from docker images they effectively try to perform docker in docker deployment.

For example if try to deploy ticktock stream (`time | log`) using docker apps images, the local deployer will generate the following docker command and run it from within the Skipper runtime (which is already a docker container): 
```
docker run -e=SPRING_APPLICATION_JSON={"endpoints.jmx.unique-names":"true","spring.cloud.dataflow.stream.app.label":"time","endpoints.shutdown.enabled":"true","spring.cloud.stream.instanceIndex":"0","spring.cloud.stream.kafka.streams.binder.zkNodes":"zookeeper:2181","spring.cloud.stream.metrics.properties":"spring.application.name,spring.application.index,spring.cloud.application.*,spring.cloud.dataflow.*","spring.application.index":"0","spring.cloud.dataflow.stream.name":"tt1","instance.index":"0","spring.cloud.stream.kafka.streams.binder.brokers":"PLAINTEXT://kafka-broker:9092","spring.metrics.export.triggers.application.includes":"integration**","spring.cloud.stream.metrics.key":"tt1.time.${spring.cloud.application.guid}","spring.cloud.stream.bindings.output.producer.requiredGroups":"tt1","server.port":"20026","spring.cloud.stream.bindings.output.destination":"tt1.time","spring.cloud.stream.kafka.binder.zkNodes":"zookeeper:2181","spring.cloud.dataflow.stream.app.type":"source","spring.cloud.application.guid":"20026","spring.cloud.stream.kafka.binder.brokers":"PLAINTEXT://kafka-broker:9092","spring.jmx.default-domain":"tt1.time-v1","spring.cloud.application.group":"tt1"} -p=20026:20026 springcloudstream/time-source-kafka:2.1.1.RELEASE
```
Later will complain that the `docker` client command doesn't exist in the target environment, e.g inside the Sipper's docker container. 
But even we install docker client in Skipper's image, we still will be lacking Docker daemon in the container as running Docker in  docker is not trivial and furthermore discouraged approach. 

Perhaps one direction to explore is to see if a docker client running inside a docker container can be connected to the Docker daemon in the host machine.

**Comment by derrick-solstice** [comment] 2019-11-25 21:03
@tzolov that was my concern.  This feels like it's a "wont-fix" type of problem.  

Should I just put up a PR to update the documentation for local deployment to mention that Docker containers are not supported for the `docker-compose` startup?

**Comment by tzolov** [comment] 2019-11-26 11:43
@derrick-solstice,  it will be "fixed" but likely in some of the minor releases following the forthcoming GA!
In fact i did a POC that you can play with it: https://bit.ly/37GhcTm 
But as you can see the issue stretches (and goes beyond) Docker's capabilities and requires further testing, additional work and polishing.  
Mind that as everything related to the local installation it is only meant for testing and development purposes.

**Comment by AnakinPt** [comment] 2020-03-17 17:42
Would not be enough to install docker in both images, and then just mount the docker socket as a volume?

**Closed** 2020-09-23 16:35 UTC

**Comment by Reddy1990** [comment] 2021-06-14 13:05
Is there any direct implementation for this docker-to-docker issues rather than using workaround ? I mean is the implementation available now?

**Comment by sabbyanandan** [comment] 2021-06-14 18:27
@Reddy1990: https://dataflow.spring.io/docs/installation/local/docker/#docker-stream--task-applications -- please ask questions like this in StackOverflow going forward.
