### ISSUE TITLE
Cannot launch composed tasks

### ISSUE THREAD

**Issue by aruiz14** [spring-cloud/spring-cloud-dataflow#5072] opened 2022-08-31 15:25 UTC
**Description:**

Trying to launch a very simple composed task definition results in the following error:
```
Failed to resolve MavenResource: org.springframework.cloud:spring-cloud-dataflow-composed-task-runner:jar:@dataflow.version@. Configured remote repository: : [springRepo]
```

**Release versions:**
I think that only the latest 2.9.5 version is affected, while 2.9.4 works well.

**Steps to reproduce:**

1. Start from a fresh installation.
2. Add applications
2.1 "Stream application starters for RabbitMQ/Maven"
2.2 "Task application starters for Maven"
3. Create a dummy composed task, with definition: `1: timestamp && 2:timestamp`
4. Go to the new task and try to launch it

**Screenshots:**
![Screenshot 2022-08-31 at 15 44 06](https://user-images.githubusercontent.com/4057165/187716299-3598efd0-d104-4316-8b8a-c2876a57e334.png)

**Additional context:**
From what I could observe, I think it's a problem with a variable interpolation affecting the `spring.cloud.dataflow.task.composedtaskrunner.uri` property in the `spring-cloud-dataflow-server-core` module. Probably missing from this PR ( #5014 ). I downloaded and extracted [the `.jar` file](https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-server-core/2.9.5/spring-cloud-dataflow-server-core-2.9.5.jar) for this version and I could check how [`spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml`](https://github.com/spring-cloud/spring-cloud-dataflow/blob/720ebd0a209a37518e8aa1147be2871db605466e/spring-cloud-dataflow-server-core/src/main/resources/META-INF/dataflow-server-defaults.yml) still contained `@dataflow.version@`:
```
META-INF/dataflow-server-defaults.yml
110:          uri: "maven://org.springframework.cloud:spring-cloud-dataflow-composed-task-runner:@dataflow.version@"
```

**Comment by onobc** [comment] 2022-09-01 17:51
@aruiz14 thank you for the report and digging into the cause. We will get this addresses ASAP. In the meantime...

### Workaround
Specify the property manually such as:
```
spring.cloud.dataflow.task.composedtaskrunner.uri=maven://org.springframework.cloud:spring-cloud-dataflow-composed-task-runner:2.9.5
```
OR as env var:
```
SPRING_CLOUD_DATAFLOW_TASK_COMPOSEDTASKRUNNER_URI=maven://org.springframework.cloud:spring-cloud-dataflow-composed-task-runner:2.9.5
```

ℹ️ **NOTE** Since this resolved into a configuration properties of a core SCDF component at context load time, this can not be specified add a deployment or app property at launch time.

**Comment by markpollack** [comment] 2022-09-08 14:38
Will make a 2.9.6 release to address this.

**Closed** 2022-09-12 15:11 UTC
