### ISSUE TITLE
spring-cloud-dataflow - Unable to redeploy a stream after undeploying 

### ISSUE THREAD

**Issue by pravinkumarb84** [spring-cloud/spring-cloud-dataflow#4980] opened 2022-07-01 19:40 UTC
### Name and Version

bitnami/spring-cloud-dataflow 11.0.4

### What steps will reproduce the bug?

Deployed bitnami/spring-cloud-dataflow 11.0.4 helm chart with external DB as postgres.

dataflow server - bitnami/spring-cloud-dataflow:2.9.4-debian-11-r3
skipper - bitnami/spring-cloud-skipper:2.8.4-debian-11-r3

Deployed a sample stream - logtest=rabbit-source | log-sink

It got deployed and when try to undeploy it and redeploy it. I have 2 issues.

1. I am unable to deploy. Error from skipper log

```
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 27, column 5:
        "spring.cloud.deployer.kubernete ... 
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 28, column 740:
     ... From: { fieldRef: { fieldPath: "metadata.labels['spring-group-id ...                                          ^
```

Issue 2: In the dashboard, when I view stream definition, I see additional properties getting added for metrics and wavefront which adds difficulty in getting stream definition. How to disable this feature of adding additional properties for metrics and wavefront.

```
rabbit-source --wavefront.application.service=${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}} --management.metrics.tags.application.type=${spring.cloud.dataflow.stream.app.type:unknown} --management.metrics.tags.stream.name=${spring.cloud.dataflow.stream.name:unknown} --management.metrics.tags.application=${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown} --management.metrics.tags.application.guid=${spring.cloud.application.guid:unknown} --rabbit.queues=test1 --management.metrics.tags.application.name=${vcap.application.application_name:${spring.cloud.dataflow.stream.app.label:unknown}} --management.metrics.tags.instance.index=${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}} --wavefront.application.name=${spring.cloud.dataflow.stream.name:unknown} | log-sink --wavefront.application.service=${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown}-${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}} --management.metrics.tags.application.type=${spring.cloud.dataflow.stream.app.type:unknown} --management.metrics.tags.stream.name=${spring.cloud.dataflow.stream.name:unknown} --management.metrics.tags.application=${spring.cloud.dataflow.stream.name:unknown}-${spring.cloud.dataflow.stream.app.label:unknown}-${spring.cloud.dataflow.stream.app.type:unknown} --management.metrics.tags.application.guid=${spring.cloud.application.guid:unknown} --management.metrics.tags.application.name=${vcap.application.application_name:${spring.cloud.dataflow.stream.app.label:unknown}} --management.metrics.tags.instance.index=${vcap.application.instance_index:${spring.cloud.stream.instanceIndex:0}} --wavefront.application.name=${spring.cloud.dataflow.stream.name:unknown}
```

### Are you using any custom parameters or values?

No

### What is the expected behavior?

Streams should be redeployed

### What do you see instead?

```
org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 27, column 5:
        "spring.cloud.deployer.kubernete ... 
        ^
expected <block end>, but found '<scalar>'
 in 'reader', line 28, column 740:
     ... From: { fieldRef: { fieldPath: "metadata.labels['spring-group-id ... 
```

**Comment by markpollack** [comment] 2022-07-27 15:29
Regarding issue 1:  We have not been able to reproduce this behavior on our side.  We will look to make the error message show the full yaml document.  It looks like the YAML stored in the skipper database is invalid somehow.  Is it possible in the meantime for you to connect directly to the database and get the full yaml.  Also, can you send the full stack trace, that would help.  it might be on the server side logs.

For issue 2, it is a different issue, so moving it to another github issue number so that there is one gh issue per issue.

**Comment by markpollack** [comment] 2022-07-27 15:31
Created https://github.com/spring-cloud/spring-cloud-dataflow/issues/5038

**Comment by markpollack** [comment] 2022-09-22 14:08
Closing as not enough information to reproduce.  Feel free to create a new issue.

**Closed by markpollack** 2022-09-22 14:08 UTC
Labels: status/need-feedback
