### ISSUE TITLE
TaskSchedulerController - Nullpointer Exception when retrieving non-existing Schedule

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#2310] opened 2018-07-10 01:44 UTC
In `TaskSchedulerController` we should check for non-existing schedules and return a `404` instead of a `500` Http Status code:

```java
	@RequestMapping(value = "/{name}", method = RequestMethod.GET)
	@ResponseStatus(HttpStatus.OK)
	public ScheduleInfoResource getSchedule(
			@PathVariable("name") String scheduleName) {
		return taskAssembler.toResource(this.schedulerService.getSchedule(scheduleName));
	}
```

```json
[{"logref":"NullPointerException","message":"NullPointerException"}]
```

Stacktrace:

```
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 2018-07-10 01:33:45.215 ERROR 18 --- [nio-8080-exec-6] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT java.lang.NullPointerException: null
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController$Assembler.toResource(TaskSchedulerController.java:166) ~[spring-cloud-dataflow-server-core-1.6.0.BUILD-SNAPSHOT.jar!/:1.6.0.BUILD-SNAPSHOT]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at org.springframework.cloud.dataflow.server.controller.TaskSchedulerController.getSchedule(TaskSchedulerController.java:100) ~[spring-cloud-dataflow-server-core-1.6.0.BUILD-SNAPSHOT.jar!/:1.6.0.BUILD-SNAPSHOT]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
   2018-07-09T15:33:45.21-1000 [APP/PROC/WEB/0] OUT 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.18.RELEASE.jar!/:4.3.18.RELEASE]
```

**Comment by tzolov** [comment] 2018-07-10 15:44
It seems that the root cause of this issue lays in the `spring-cloud-scheduler-cloudfoundry` library. I've created https://github.com/spring-cloud/spring-cloud-scheduler-cloudfoundry/issues/21 ticket there: @cppwfs

I the meantime i can create a NPE exception handling SCDF controller for additional robustness

**Comment by tzolov** [comment] 2018-07-10 15:52
This will be fixed in spring-cloud/spring-cloud-scheduler-cloudfoundry#21

**Comment by cppwfs** [comment] 2018-07-10 16:02
This issue is when Gunnar is trying to get a specific schedule from dataflow. i.e.  http://localhost:9393/tasks/schedules/<non-existent-schedule-name>

**Comment by tzolov** [comment] 2018-07-10 16:35
There `/tasks/schedules/` request hits the [TaskSchedulerController#list](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/TaskSchedulerController.java#L80) that in turn hits [DefaultSchedulerService#list()](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultSchedulerService.java#L164), that in turn calls the [CloudFoundryAppScheduler#list()](https://github.com/spring-cloud/spring-cloud-scheduler-cloudfoundry/blob/master/src/main/java/org/springframework/cloud/scheduler/spi/cloudfoundry/CloudFoundryAppScheduler.java#L125) within which the NPE is thrown. 

The `TaskSchedulerController` and `DefaultSchedulerService` classes are part of the SCDF server, but the `CloudFoundryAppScheduler` (where the NPE occurs) is part fo the `spring-cloud-scheduler-cloudfoundry` implementation.

As mentioned earlier, if necessary we can implement a workaround patch in the SCDF server? 

Still the NPE issue lays in spring-cloud-scheduler-cloudfoundry and should be addressed there

**Comment by tzolov** [comment] 2018-07-10 17:45
Apparently the above behavior is not related to the reported issue and is caused by the fact that there was not a Scheduler service created in the test CF space. 

The original issue is related to the fact that a request for non existing service throws NPE rather then returning  HTTP 404.

**Closed** 2018-07-11 17:53 UTC
Labels: bug 🐞, in pr
