### ISSUE TITLE
Sensitive information like Datasource username and Password are Exposed

### ISSUE THREAD

**Issue by janamailzuu** [spring-cloud/spring-cloud-dataflow#3985] opened 2020-06-03 17:29 UTC
**Description:**
SCDF(2.5.1.RELEASE) is in Kubernetes. We have noticed SCDF exposes sensitive information like spring.datasource.username and spring.datasource.password in multiple places.
	1. Running a kubectl describe pod on the task pod.
	2. task_execution_manifest column in task_execution_metadata table.
	3. Task pod logs/ the log section of any specification taks execution from dashboard.

We have a database secret created and referenced them by following these docs[General Secret configuration](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-kubernetes-general) and [Database Configuration](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-kubernetes-rdbms). When we launch a task from SCDF, it just adds the datasource properties as environment variables/command line arguments. 

We have also configured some secret key references globally for the tasks by following these configuration.[Secret Key References](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_secret_key_references). That is passing the secret key reference as expected instead of passing the actual values.

We have also tried tried changing the entryPointStyle by following [Application Properties With Sensitive Information on Kubernetes](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_application_properties_with_sensitive_information_on_kubernetes), the only difference we noticed is the place where we see the senstive information. It didn't help any and the documentation sounds misleading. 

**Release versions:**
2.5.1.RELEASE. 
[SCDFAboutResponse.txt](https://github.com/spring-cloud/spring-cloud-dataflow/files/4725067/SCDFAboutResponse.txt)

**Custom apps:**
Issue applicable to any app

**Steps to reproduce:**
1. Launch a task from the dashboard/Schedule them.
2. check the task pods created.
3. Run the command kubectl describe pod <taskPodName>
4. Run the command kubectl logs -f <taskPodName>
5. check the task_execution_manifest column of task_execution_metadata table.

Expectation:
We would want the database secrets to be passed as secretKeyRefs instead of actual values.

**Comment by SebastianGoeb** [comment] 2020-06-04 07:51
For K8s, the helm chart already deploys a database-secret or uses mysql's own secret for server/skipper., so it wouldn't be such a stretch wire the same secret into the deployer.

**Comment by chrisjs** [comment] 2020-06-04 20:20
`secretKeyRefs` would work, i have a PR in flight for `secretRefs` which would allow sucking all data keys in from a secret rather than specifying individual keys as well if that's desirable

**Comment by janamailzuu** [comment] 2020-06-04 20:25
@chrisjs SecretKeyRefs passed to the task are looking good. But SCDF adds the datasource username and password(plain text) as command line arguments.
Please check updateTaskProperties method in [TaskServiceUtils class](https://github.com/spring-cloud/spring-cloud-dataflow/blob/7c14121ccc2040bb4bf0eacdba232ce352b1ffd9/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/TaskServiceUtils.java). We have a database secret in the helm chart. I would expect it to pass the database secret instead of passing the username and password as plain text.

**Comment by chrisjs** [comment] 2020-06-04 20:28
understood. see above, was making reference to your `secretKeyRef` usage and the general comment that `secretRefs` will be available soon. edited my comment to add a quote, might not have done it prior to your response.

**Comment by sabbyanandan** [comment] 2020-06-04 20:39
@janamailzuu: We don't do anything different in SCDF in regards to how the properties are passed and persisted. We do, however, redact sensitive properties from being visibly presented in the SCDF client tools, including REST-APIs, Shell, DSL, and the GUI. The content that gets shared along and persisted in the tables is stored as-is also. 

Likewise, any Spring Boot properties (eg: datasource creds) are expected by the application to be interpreted as such, as opposed passed as `secretKeyRefs` or any other primitive that only can work on K8s.

**Comment by miller79** [comment] 2020-06-04 20:48
@sabbyanandan we definitely understand what you mean however the docs specifically state about using [ConfigMap and Secrets](https://docs.spring.io/spring-cloud-dataflow/docs/2.5.1.RELEASE/reference/htmlsingle/#_using_configmap_and_secrets) for the Datasource.  The issue is when a task is executed, that value is no longer a secret reference but now just an environment variable (or in the JSON) depending on the `entryPointStyle`.  We don't really have any control over that particular setting outside of that so I'm wondering your thoughts on those specific settings (focusing mainly on `spring.*.datasource.password`)

**Comment by chrisjs** [comment] 2020-06-04 21:18
the `Using ConfigMap and Secrets` section is showing how to configure boot properties via configmap which reference a secret key and resolved via spring cloud kubernetes. thats all well and good for the application itself, but the problem your seeing specifically would be as @janamailzuu pointed out, in this area:

https://github.com/spring-cloud/spring-cloud-dataflow/blob/7c14121ccc2040bb4bf0eacdba232ce352b1ffd9/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/TaskServiceUtils.java#L112

where the datasource properties are being packaged up and shipped off to the deployer which are then in turn passed as cmd args or env vars on the container based on entrypointstyle and visible when describing a pod.

to avoid that, a secret ref would rather be passed to the deployer to hide that info yet allow it to be populated into the environment and would not be shown in the describe output.

obviously would could just run `printenv` via `exec` on the pod and see the decoded environment variable unless `exec` is restricted, but we understand your point

**Comment by miller79** [comment] 2020-06-04 21:30
If I'm understanding you correctly, are you suggesting that we could use a `secretRef` currently and potentially stop the information from being seen now or are we locked in the current version due to the `TaskServiceUtils` until the alternate options are available?

**Comment by chrisjs** [comment] 2020-06-04 21:32
the taskserviceutils code will run regardless

________________________________

**Comment by janamailzuu** [comment] 2020-06-04 21:41
> to avoid that, a secret ref would rather be passed to the deployer to hide that info yet allow it to be populated into the environment and would not be shown in the describe output.
@chrisjs Thanks for understanding! This is exactly what we are expecting. :) When can we expect this though?

**Comment by sabbyanandan** [comment] 2020-06-04 21:55
@miller79: There's yet another approach to dealing with sensitive properties that I see at a few customers. The use of config-server like a solution would provide the flexibility to securely bind the relevant apps with credentials that can be resolved at runtime. With that, you don't need to worry about `secretRef` and how to pass things around back and forth. That said, I also understand this may not be a feasible solution for some given the extra component that needs to be managed.

However we design to solve this, we should not break the existing behavior for the rest of the SCDF implementations. 

@janamailzuu: Given the current commitments and priorities, we will have to review it in that context. Feel free to start the dialog by submitting a pull-request; we are happy to collaborate.

**Comment by miller79** [comment] 2020-06-04 21:57
@sabbyanandan definitely interested in some solutions since we give our developers access to run describe in our Kubernetes so having the password shown in plain text is a show stopper for us using the tool.  We do have a config server so I'd be interested in hearing what options you are thinking using that currently or do you think that is another enhancement?

**Comment by sabbyanandan** [comment] 2020-06-04 22:09
Config-server integration should work already. SCDF is a Boot app, so nothing new is required to have it work against it. We don't have any prescription on how to setup Config Server on K8s, though (it is not part of the product that we ship). The Spring Commercial team is working on productizing Config Server for Kubernetes, however.

For now, though, you will have to provision it on K8s on your own (like other customers), and launch your task apps pointing to the config-server repository.

**Comment by janamailzuu** [comment] 2020-06-04 22:32
> There's yet another approach to dealing with sensitive properties that I see at a few customers. The use of config-server like a solution would provide the flexibility to securely bind the relevant apps with credentials that can be resolved at runtime. With that, you don't need to worry about `secretRef` and how to pass things around back and forth.

@sabbyanandan We do use our config-server for fetching Task specific properties. Just to understand correct, Are you saying if we use config-server to supply the datasource properties and let the credentials resolve at runtime, we will not face this issue with the current SCDF version or suggesting this as an alternate enhancement approach for fixing this issue?

**Comment by sabbyanandan** [comment] 2020-06-04 22:37
If you don't pass them via SCDF to tasks instead resolve them from Config Server, those properties won't land in the env-vars. This is a plain old Config Server value proposition; nothing SCDF related.

**Comment by cppwfs** [comment] 2020-06-04 22:45
@sabbyanandan I think dataflow will still send the db properties over for each launch.

**Comment by miller79** [comment] 2020-06-05 14:45
> @sabbyanandan I think dataflow will still send the db properties over for each launch.

From what I can see this looks to be the case as well which is why I'm curious if there is any way to disable this or change the way it works currently.

**Comment by Srkanna** [comment] 2020-06-19 12:13
So as per the conversation my understanding is the DB properties are exposed even when we go with Config-server. is that correct @sabbyanandan ?
I deployed the config-server and the db properties were still passed in plain text from SCDF. Right now my team thinks of using seprate schema delegated for these task tables to isolate it from business schema.

**Comment by cppwfs** [comment] 2020-09-14 19:05
Linking this issue https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/389 to resolve the ability to support secrets in schedules.

**Closed** 2020-09-19 00:43 UTC
Labels: contributions welcome, enhancement
