### ISSUE TITLE
TASK EXECUTION DELETE API does not seem to work.

### ISSUE THREAD

**Issue by annasarte** [spring-cloud/spring-cloud-dataflow#1845] opened 2017-12-19 23:03 UTC
We are on spring cloud data flow server version 1.2.3.
Running this on Linux.
We are able to create and launch tasks.
However, **deleting a task execution via the REST API,** I receive an http status code of 200 (OK) but the task still remains.
Steps:

1) launch a task -- your response is a job / execution id
2) via REST api, you can list this task execution . Ex: GET http://localhost:9393/tasks/executions/1
3) delete this task execution via REST api: DELETE http://localhost:9393/tasks/executions/1
4) You can look at the database tables and the table TASK_EXECUTION still lists this job
repeat getting/listing this task execution : GET http://localhost:9393/tasks/executions/1 and again, you will see it listed.

Anything I need to be doing?
Thanks,
Anna

**Comment by mminella** [comment] 2017-12-19 23:07
I'm closing this as a duplicate of #1844 .  We can continue the conversation there and if we need to re-open #1844, we can do so.  Please do not keep opening new issues for this.

**Closed by mminella** 2017-12-19 23:07 UTC
