### ISSUE TITLE
Chinese and Japanese garbled characters appear

### ISSUE THREAD

**Issue by yuhuyuyu** [spring-cloud/spring-cloud-dataflow#5040] opened 2022-08-01 11:08 UTC
**Description:**
Create a stream containing a script application. If the script contains Japanese or Chinese, some errors will occur.
1. SQLException occurs when deploying
This is because the encoding method of the date field of skipper_manifest and the pkg_json_string field of skipper_release in skipper database is latin1. So I changed the encoding of the field to utf8, which solved the problem.
2. The problem of garbled characters
After I solved problem 1, I checked skipper_release and skipper_manifest, and found that both Japanese or Chinese are in the table? ? ? (garbled state). I still don't know how to solve this problem.

**Release versions:**
spring cloud dataflow  2.9.0
script application 3.2.1

**Steps to reproduce:**
```
http | script --language=python --script=payload=payload+'嗨你好世界' | log
```

**Screenshots:**
Where applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/67989582/182133610-1da648ce-bfc9-428b-9a07-271256ef9393.png)

**Comment by corneil** [comment] 2022-08-04 11:27
@onobc This seems similar to a recent issue you dealt with.

**Comment by corneil** [comment] 2022-10-20 13:18
After setting Database encoding to UTF-8 I was able to save the DSL.
Using: `kubectl exec kafka-broker-0 -- /usr/bin/kafka-console-consumer --bootstrap-server localhost:9092 --whitelist ".*"` to log to message on topic from kafka does show the message with the kanji and not the ???
This means that despite setting container and Java default encoding to UTF-8 the log-sink still prints ??? instead of kanji.

**Comment by corneil** [comment] 2022-10-24 10:35
The root cause of this lies in the baseimage used by Spring Cloud Stream Applications.
I propose updating the build process to use packeto buildpacks like Spring Boot build image and existing Spring Cloud Data Flow builds. We can publish images for Java 8, 11 and 17 and tag 11 as the default for the version like we do with SCDF.

**Comment by corneil** [comment] 2022-10-27 21:33
The snapshot images has been created with Packeto Buildpacks like Spring Boot images.
They can be registered with [https://repo.spring.io/snapshot/org/springframework/cloud/stream/app/stream-applications-descriptor/2021.1.3-SNAPSHOT/stream-applications-descriptor-2021.1.3-SNAPSHOT.stream-apps-kafka-docker](https://repo.spring.io/snapshot/org/springframework/cloud/stream/app/stream-applications-descriptor/2021.1.3-SNAPSHOT/stream-applications-descriptor-2021.1.3-SNAPSHOT.stream-apps-kafka-docker)

The application versions are `3.2.2-SNAPSHOT`

The default encoding for the container and JVM have been set using to en_US.UTF-8 using environmental variables `LANG=en_US.utf8`, `LC_ALL=en_US.utf8` and `JDK_JAVA_OPTIONS=-Dfile.encoding=UTF-8 -Dsun.jnu.encoding`

Users will only need to update `LANG` or `LC_ALL` if they need a different locale.

**Comment by corneil** [comment] 2022-11-04 10:39
Fixed in SNAPSHOT builds.

**Closed by corneil** 2022-11-04 10:39 UTC
Labels: status/need-investigation
