### ISSUE TITLE
Adopt dependencies to versions in Camden.SR2

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow#983] opened 2016-11-02 17:11 UTC
To go along with the version changes in the deployer - https://github.com/spring-cloud/spring-cloud-deployer/issues/138

**Comment by trisberg** [comment] 2016-11-02 17:18
These changes need to be coordinated with #976

**Comment by markpollack** [comment] 2016-11-07 21:48
Closed as duplicate of https://github.com/spring-cloud/spring-cloud-dataflow/pull/994

**Closed by markpollack** 2016-11-07 21:48 UTC
Labels: in pr
