### ISSUE TITLE
Same named SCDF Task fails when previous task fails for Cloud Foundry

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow#4251] opened 2020-11-16 14:07 UTC
SCDF for Cloud Foundry version 2.6.2.  

The customer is easily able to trip up Data flow when updating a task of the same name.

The root of the issue is that SCDF Shell does not have a proper Task update command.**
This causes the customer to delete the task and immediately create a new task of the same name.
It seems the timing of it causes an issue where errors arise

(This issue is Amplified or seems to be activated faster when a task application hangs on CF and needs manual intervention like killing the task app or deleting it. That makes SCDF get out of whack further and a new task cannot be created of the same name and execute properly)
Reproduction Steps
1) Create a multiple task definitions and deploy them all with successful runs.
2) Delete a task Definition using the SCDF shell.
3) Create a new Task Definition with the same name. (within a few seconds of step 2 if not immediately after via the SCDF shell)
4) Deploy the same named task Definition.
5) Deploy one of the other pre-existing Task Deployments.

**Comment by mminella** [comment] 2020-11-16 15:32
Is the root of this really that SCDF doesn't have a "proper Task update command" or just that we are not handling the cleanup and state management under the delete properly? AKA, letting someone create a new definition based on the old one if we haven't finished cleaning things up feels like a state management issue...

**Comment by cppwfs** [comment] 2020-11-16 16:20
Its more of a cleanup issue IMHO.
This is transcribed from a discussion I had.   This issue can be amended as this issue is reviewed.

**Comment by sabbyanandan** [comment] 2021-02-26 17:46
Resolved by https://github.com/spring-cloud/spring-cloud-dataflow/issues/4267.

**Comment by sabbyanandan** [comment] 2021-05-11 15:49
Not able to reproduce this in our test environments.

**Closed by sabbyanandan** 2021-05-11 15:49 UTC
Labels: status/need-investigation, type/bug
