### ISSUE TITLE
Stream DSL does not accept properties without value

### ISSUE THREAD

**Issue by driesva** [spring-cloud/spring-cloud-dataflow#3720] opened 2019-12-31 06:53 UTC
**Description:**
We are evaluating SCDF and one of the things we wanted to test is the retry mechanisms of the RabbitMQ binder. When following the [steps as described in Spring Cloud Stream docs](https://cloud.spring.io/spring-cloud-stream-binder-rabbit/multi/multi__retry_with_the_rabbitmq_binder.html), we encounter an error when deploying the stream.
Basically it seems not possible to define a stream having a property without value. Although according to Spring Cloud Stream the following is valid:
`spring.cloud.stream.rabbit.bindings.input.consumer.dlq-dead-letter-exchange=`

Below the actual stacktrace when deploying (a simplified expression). Note that skipper successfully deploys the stream (and the RabbitMQ retry mechanism is also working as expected). However DataFlow server is unable to persist the stream definition.
```
2019-12-31 07:03:21.555 ERROR 48168 --- [io-9393-exec-11] o.s.c.d.s.c.RestControllerAdvice         : Caught exception while handling a request

org.springframework.cloud.dataflow.core.dsl.CheckPointedParseException: 105E:(pos 81): Expected an argument value but was 'null'
time --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange= | log --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=
    *                                                                            ^

	at org.springframework.cloud.dataflow.core.dsl.Tokens.raiseException(Tokens.java:277)
	at org.springframework.cloud.dataflow.core.dsl.AppParser.eatArgValue(AppParser.java:152)
	at org.springframework.cloud.dataflow.core.dsl.AppParser.eatAppArgs(AppParser.java:124)
	at org.springframework.cloud.dataflow.core.dsl.AppParser.eatApp(AppParser.java:89)
	at org.springframework.cloud.dataflow.core.dsl.StreamParser.eatAppList(StreamParser.java:377)
	at org.springframework.cloud.dataflow.core.dsl.StreamParser.eatStream(StreamParser.java:156)
	at org.springframework.cloud.dataflow.core.dsl.StreamParser.parse(StreamParser.java:74)
	at org.springframework.cloud.dataflow.core.StreamDefinition.getAppDefinitions(StreamDefinition.java:111)
	at org.springframework.cloud.dataflow.core.StreamDefinition.<init>(StreamDefinition.java:88)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.updateStreamDefinitionFromReleaseManifest(DefaultStreamService.java:208)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.doDeployStream(DefaultStreamService.java:159)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService.deployStream(DefaultStreamService.java:426)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService$$FastClassBySpringCGLIB$$89697014.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:750)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.springframework.cloud.dataflow.server.service.impl.DefaultStreamService$$EnhancerBySpringCGLIB$$5663a77.deployStream(<generated>)
	at org.springframework.cloud.dataflow.server.controller.StreamDeploymentController.deploy(StreamDeploymentController.java:183)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Release versions:**
We are getting this on 2.2.2.RELEASE but we were able to reproduce with 2.3.0.RELEASE docker compose install. The info about the 2.3.0 docker version:
```
{
  "versionInfo": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.3.0.RELEASE"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.3.0.RELEASE"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "2.3.0.RELEASE"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.3.0.RELEASE",
      "url": "https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/2.3.0.RELEASE/spring-cloud-dataflow-shell-2.3.0.RELEASE.jar"
    }
  },
  "featureInfo": {
    "streamsEnabled": true,
    "tasksEnabled": true,
    "schedulesEnabled": false,
    "grafanaEnabled": false
  },
  "securityInfo": {
    "isAuthenticationEnabled": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "platformSpecificInfo": {},
      "deployerImplementationVersion": "2.2.1.RELEASE",
      "deployerName": "Spring Cloud Skipper Server",
      "deployerSpiVersion": "2.2.1.RELEASE",
      "javaVersion": "1.8.0_192",
      "platformApiVersion": "",
      "platformClientVersion": "",
      "platformHostVersion": "",
      "platformType": "Skipper Managed",
      "springBootVersion": "2.2.1.RELEASE",
      "springVersion": "5.2.1.RELEASE"
    },
    "taskLaunchers": [
      {
        "platformSpecificInfo": {},
        "deployerImplementationVersion": "2.1.0.RELEASE",
        "deployerName": "LocalTaskLauncher",
        "deployerSpiVersion": "2.1.0.RELEASE",
        "javaVersion": "1.8.0_192",
        "platformApiVersion": "Linux 4.9.184-linuxkit",
        "platformClientVersion": "4.9.184-linuxkit",
        "platformHostVersion": "4.9.184-linuxkit",
        "platformType": "Local",
        "springBootVersion": "2.2.1.RELEASE",
        "springVersion": "5.2.1.RELEASE"
      }
    ]
  },
  "grafanaInfo": {
    "url": "",
    "token": "",
    "refreshInterval": 15
  }
}
```

**Steps to reproduce:**
Create and deploy a stream with following commands:
```
dataflow:>stream create sample --definition "time | log"
dataflow:>stream deploy --name sample --properties "app.*.spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange="
```

**Screenshots:**
In the dashboard this is also considered as invalid:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/29454303/71612336-0d880080-2ba0-11ea-82a4-d2d5e20efade.png">

**Comment by sabbyanandan** [comment] 2019-12-31 16:39
@driesva: There appears to be a limitation due to validation. We look for values and when it is not supplied, the validation won't allow you to pass, unfortunately. We will revisit to see how to allow empty values in the DSL — it is a valid option for some of the properties.

In the meantime, you could drop all the k/v pairs in a property file, and when deploying the stream, you can point the property file via: `--propertiesFile <YOUR_FILE_WITH_PROPS>

_Example:_
```
dataflow:>stream create foo --definition "time | log"

dataflow:>stream deploy --name foo --propertiesFile /Users/sanandan/Downloads/foo.txt
```

**Comment by driesva** [comment] 2020-01-02 05:47
@sabbyanandan 
We already tried the option of putting everything in a property file, but that results in the same error:
```
dataflow:>stream deploy --name foo --propertiesFile /tmp/foo.properties
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 105E:(pos 81): Expected an argument value but was 'null'
time --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange= | log --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=
    *                                                                            ^

105E:(pos 81): Expected an argument value but was 'null'
time --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange= | log --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=
    *                                                                            ^

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 105E:(pos 81): Expected an argument value but was 'null'
time --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange= | log --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=
    *                                                                            ^

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:65)
    at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:778)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:736)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:670)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:414)
    at org.springframework.cloud.dataflow.rest.client.StreamTemplate.deploy(StreamTemplate.java:127)
    at org.springframework.cloud.dataflow.shell.command.StreamCommands.deployStream(StreamCommands.java:166)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:68)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:59)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:134)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by olegz** [comment] 2020-01-02 05:51
What is the purpose of defining property without any value? Just curious. . . Also what is your intention with this `...dlqDeadLetterExchange= | log`?

**Comment by driesva** [comment] 2020-01-02 05:54
We were trying out retry capabilities for RabbitMQ as per [documentation](https://cloud.spring.io/spring-cloud-stream-binder-rabbit/multi/multi__retry_with_the_rabbitmq_binder.html):

> Set the dlqDeadLetterExchange to the default exchange. Expired messages from the DLQ are routed to the original queue, because the default deadLetterRoutingKey is the queue name (destination.group). Setting to the default exchange is achieved **by setting the property with no value**, as shown in the next example.

**Comment by jvalkeal** [comment] 2020-01-02 10:08
Using `dlqDeadLetterExchange` as an empty value is anyway not going to work in a future because on a stream side we're going to do same property handling as we did on a task side. As tasks internally moved to use a manifest we currently rely on a fact that if value is empty that instructs removal of that property from a manifest. We didn't yet start this work on a stream side.

There probably should be a separate property doing same as setting `dlqDeadLetterExchange` empty.

**Comment by sabbyanandan** [comment] 2020-01-13 23:47
@driesva: While reviewing this with @aclement today, he mentioned using the `""` as the value, and that should allow you to deploy the properties without any explicit value.

In your case, the DSL would then be:

> time --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange="" | log --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=""

I hope this helps. In the meantime, we will revisit this to improve the experience further.

**Comment by driesva** [comment] 2020-01-14 07:47
@sabbyanandan that's a workaround for creating the stream in the editor, but as soon as you deploy, the issue appears. It seems the stream is stored without the `""` Both when using the shell or UI editor.

When using shell:

```
dataflow:>stream create --name test --definition "time --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=\"\" | log --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=\"\""
```
or
```
dataflow:>stream create --name test --definition 'time --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange="" | log --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=""'
```
Gives following definition:
```
dataflow:>stream info test
╔═════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╤═══════════╤══════════╗
║ Stream  │                                                         Stream Definition                                                          │Description│  Status  ║
║  Name   │                                                                                                                                    │           │          ║
╠═════════╪════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪═══════════╪══════════╣
║test     │time --spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange= | log                                              │           │undeployed║
║         │--spring.cloud.stream.rabbit.bindings.input.consumer.dlqDeadLetterExchange=                                                         │           │          ║
╚═════════╧════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╧═══════════╧══════════╝
```

**Comment by aclement** [comment] 2020-07-07 22:11
I think, as per one of the comments above:
```
It seems the stream is stored without the "" Both when using the shell or UI editor.
```
The fix is not to allow the parser to accept empty values (i.e. an `=` with nothing after) . It is in the code that rebuilds the stream DSL once deployed to recognize an empty parameter value and quote it so that it will parse correctly. I think that code should really be trying to produce the same DSL that was used to create the stream in the first place.

**Comment by ilayaperumalg** [comment] 2020-07-08 15:05
@aclement We can fix this at the backend where we reconstruct the stream DSL. Looks like the Skipper side also requires a fix to handle reading the manifest with the empty value when the stream gets deployed.

**Comment by ilayaperumalg** [comment] 2020-07-28 17:41
Tried to update the fixes on SCDF and Skipper but it breaks some of the data flow UI stream parser when trying to deploy the stream. We don't want to introduce any regression at this point of time in 2.6.0 as we plan to do GA soon. Moving this to 2.7 timeline. Sorry about the delay in checking this out.

**Closed** 2020-09-30 13:47 UTC
Labels: backport-2.6.x, bug 🐞
