### ISSUE TITLE
REST: Stream Definition List - Pagination with Search Filter gives incorrect results

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow#1598] opened 2017-07-14 15:49 UTC
When using a filter list correctly shown filtered entries but original pagination number is still reflected. i.e if you have 30 defs, filter gives only one, there should be on one page.

This is depended on by https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/257

See also: https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/controller/StreamDefinitionController.java#L201

**Comment by jvalkeal** [comment] 2017-07-14 16:09
@sabbyanandan Feel free to take it away from 1.2.3 if you don't want this fixed by then. I'm anyway trying to PR fix for this.

**Comment by jvalkeal** [comment] 2017-07-17 05:20
This turned out to be a little more complex issue than just a simple bug fix. It's caused by `AbstractRdbmsKeyValueRepository.search(SearchPageable)` always returning pagination `totalSize` as count of all values (per repository count() method) which is wrong if filtering is used. `PagingQueryProvider` does filtering with pagination so it hides `filtered` size we should use to show accurate paging. Looks like on a conceptual level `PagingQueryProvider` needs to be changed so that it can also give out filtered size.
It's a big change which feels a bit dangerous at a list minute before a release.

**Closed** 2017-07-21 09:01 UTC
Labels: bug, in pr
