### ISSUE TITLE
Feature request: customizable composed-task-runner application  name

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow#2290] opened 2018-06-28 10:28 UTC
Hello
Would you please consider `CTR` name to be optionally provided to  `TaskExecutionController` that will default to today's hard-coded `composed-task-runner` if not specified ?
This will allow users to  provide their own implementation (by registering the CTR task app with custom name )  for specific composed tasks  cases and at the same time  to be able to run OOTB provided  `composed- task-runner` .
Thanks

**Comment by sabbyanandan** [comment] 2018-07-01 23:32
Hi, @jvmlet. What is not covered in the existing OOTB CTR? Perhaps there's an opportunity to contribute it back to the project if they are general purpose improvements for the broader community.

**Comment by jvmlet** [comment] 2018-07-03 14:35
Hello @sabbyanandan 
This feature request is about to enable the customer to provide completely different implementation from OOTB CTR.   
The CTR implements the graph execution using   `spring-batch` and `spring-cloud-task` which heavily relay on the DB. This leads to significant overhead considering  the graph  that contains many `light` steps and having relatively high frequency of CTR invocations.

We are experimenting with `embedded` task execution mode by extending the  CTR to intercept the REST calls to SCDF and launching the task  as child context. This approach requires to package the tasks together with CTR and define the CTR's graph as hard-coded property value, but on the other hand , we can still use the same task in `distributed`  (original) mode.

Another approach   to execute the graph can be implemented without `spring-batch` and using more sophisticated `completion callbacks` [(see this issue)](https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/4), like messaging middleware. We are experimenting with this as well.

At some point, it became very complected to support the original (`distributed`)  mode of CTR ,`embedded` mode and completely different implementation of DAG execution  - this was the reason for this feature request: to be able to pass the CTR name to SCDF to execute the graph with.

We  have no problem to contribute to community with embedded-mode CTR if there will be the interest for it.

**Comment by mminella** [comment] 2018-07-03 15:04
Hi @jvmlet,

Let me address each of your points:

* **Heavy reliance on the DB -** We took this approach for the ability to monitor the status of a composed task as well as to add things like restartability.  Without this functionality you'd lose all visibility into a CTR run for SCDF.  Removing this functionality doesn't feel right _as part of SCDF_.  I'm not arguing that an alternative path doesn't have a use, but when you consider the integration with SCDF it doesn't make as much sense IMHO.
* **"Embedded mode" -** I'd need to learn more about this.  How are you launching the tasks which are packaged as a Boot über jar as a child context?  This also gets dicy with regards to things like memory management, etc.  I'm not 100% sure we'd want to support this as a formal feature (this is one of the reasons we transitioned from Spring XD to Spring Cloud Data Flow).
* **Completion callbacks -** We discussed this at length in our design.  While we'd actually like to take this approach, it then requires the packaging of a binder/etc with the child tasks.  We felt that this combined with that you'd need to have a CTR for each binder implementation.  We felt that it was too large of a burden.  We discussed this in the issue you reference.  Maybe we should revisit this in some capacity...
* **Pass a name for the CTR -** To be clear, you're proposing providing your own implementation of the CTR, correct?  If so, I thought you could already do that via the way you register the CTR: https://docs.spring.io/spring-cloud-dataflow/docs/1.5.x/reference/htmlsingle/#_registering_the_composed_task_runner.  You'd just register your own.  Unless you're looking to support both mechanisms with the same SCDF server instance.

**Comment by jvmlet** [comment] 2018-07-04 15:07
Thanks for the feedback, @mminella 
I agree that monitoring and restartability  are very powerful features, but I think that  automatic deployment that targets different platforms , versioning support, scheduling  have more added value than CTR's spring-batch features. BTW, if you saw my post in gitter [here](https://gitter.im/spring-cloud/spring-cloud-dataflow?at=5b295ec2ce3b0f268d2ab919), I've instrumented the data source of CTR using [datasource-proxy](https://github.com/ttddyy/datasource-proxy), collected all the queries  during run-time and created indices based on the `WHERE` statements from logs, this is what I've applied to out postgres DB:

````sql
CREATE INDEX IF NOT EXISTS batch_job_execution_params_job_execution_id_idx ON batch_job_execution_params (job_execution_id) ;
CREATE INDEX IF NOT EXISTS task_execution_params_task_execution_id_idx ON task_execution_params (task_execution_id) ;
CREATE INDEX IF NOT EXISTS batch_job_instance_job_key_idx ON batch_job_instance (job_key,job_name) ;
CREATE INDEX IF NOT EXISTS batch_step_execution_job_execution_id_idx ON batch_step_execution (job_execution_id) ;
````

We got **1000%** of performance boost with this (of cause, depends on the size of the DB)

According to embedded mode, the **original** (not uber) tasks  jars artifacts are packed together with CTR  to bootable jar. All our tasks have this snippet in `gradle.build`:

````gradle
bootRepackage{
                classifier ='bootable'
            }
````
This simple  config  allows us to register the same task as normal bootable app task with SCDF and the `original` jar to be used in embedded mode. Also, the process's RAM (in out case it's CF task)  is shared only with the steps which are on the **same level** of CTR graph, so the memory limitation is applicable to level, not to **all**  tasks. For our case, when we have plenty of light steps (5-6) per level and  graph depth of 3-4 is OK. 

When talking about the embedded mode, I want to bring your attention to potential bug in `TaskLifecycleListener` class. It uses the wrong context when it closes it. No one will probably  ever suffer from  this , but :

![image](https://user-images.githubusercontent.com/6664858/42283244-8f1869a6-7fb1-11e8-97c6-03d65af4ba6a.png)

As you can the, see  the `doTaskEnd()` closes the `this.context`, not the application event's context. In our case, the `@Autowired this.context` is the parent app context, this prevents me from sharing beans from app context with embedded task context.  This is  how the embedded task is launched :

````java
@Configuration
@Slf4j
@EnableConfigurationProperties({ComposedTaskProperties.class,EmbeddedProperties.class})
@AutoConfigureAfter(CommonAutoconfig.class)
public class PatchedComposedTaskRunnerConfiguration {

@Bean
    @Profile(EMBEDDED_PROFILE_NAME)
    public EmbeddedRunInterceptor embeddedRunInterceptor( ){
        return new EmbeddedRunInterceptor();
    }

    
    @Bean
    public RestTemplate dfRestTemplate(){
        RestTemplate restTemplate =new RestTemplate();
        if(applicationContext.getEnvironment().acceptsProfiles(EMBEDDED_PROFILE_NAME)){
            restTemplate.getInterceptors().add(applicationContext.getBean(EmbeddedRunInterceptor.class));
        }
        return  restTemplate;
    }
}

@Slf4j
public class EmbeddedRunInterceptor implements ClientHttpRequestInterceptor {
    @Autowired
    private EmbeddedProperties embeddedProperties;

    @Autowired
    private ConfigurableApplicationContext applicationContext;



    @Qualifier("etlExecutor")
    @Autowired
    private ThreadPoolTaskExecutor etlTaskExecutor;


    @Override
    public ClientHttpResponse intercept(HttpRequest request, byte[] body, ClientHttpRequestExecution execution) throws IOException {

        if("/tasks/executions".equalsIgnoreCase(request.getURI().getPath()) && HttpMethod.POST.equals(request.getMethod())){
            TaskExecution taskExecution = applicationContext.getBean(TaskConfigurer.class).getTaskRepository().createTaskExecution();

            EmbeddedEtlTask embeddedEtlTask = new EmbeddedEtlTask(request, body, taskExecution.getExecutionId());
            embeddedEtlTask.setEmbeddedProperties(embeddedProperties);
            embeddedEtlTask.setApplicationContext(applicationContext);

            etlTaskExecutor.execute(embeddedEtlTask);
            return  new EmbeddedTaskLaunchResponse(taskExecution);

        }
        return execution.execute(request,body);
    }
}


@Slf4j
public class EmbeddedEtlTask implements Runnable {

    @Autowired
    private ConfigurableApplicationContext parentContext;

    @Override
    public void run() {
      String taskName = request.getURI().getQuery().split("=")[1];
       arguments.addAll(Arrays.asList("--spring.jmx.enabled=false",
                // other stuff
                "--spring.cloud.task.executionid="+taskExecutionId
                )
        );

        try {
            Class<?> sourceClass =Class.forName(embeddedProperties.getContextMapping().get(taskName ));
            System.setProperty(LoggingSystem.SYSTEM_PROPERTY,LoggingSystem.NONE);
            Thread.currentThread().setContextClassLoader(sourceClass.getClassLoader());

            new SpringApplicationBuilder() // this is how embedded task is launched
                    //.parent(parentContext) // can't do  this because it will be closed
                    .sources(EmbeddedTaskConfiguration.class,sourceClass)
                    .properties(propertiesToUse)
                    .run(arguments.toArray(new String[]{}));

        } catch (Throwable e) {
            log.error("Failed to run {}",taskName ,e);
        }
    }
}
````
The app is configured like this :

````yaml
embedded:
  contextMapping:
    task1: com.company.task1.MainApp
    task2: com.company.task2.MainApp
    task3: com.company.task3.MainApp
    task4: com.company.task4.MainApp
    task5: com.company.task5.MainApp

spring:
  cloud:
    task:
      name: MY_PIPELINE
graph: "<task1 || task2 > && <task3 || task4 || task5>"
````

OK, so the main point of this issue is to be able to register additional task runner with SDCDF and pass this name when invoking the task via REST endpoint. As you've mentioned, it's impossible to have more than one CTR name with the same SCDF instance. This issue is not about to support embedded mode, but let customer to register another CTR name in  addition to OOTB CTR.
Thanks

**Comment by mminella** [comment] 2018-07-05 17:14
First of all, thank you @jvmlet for such a detailed response.  A few notes:
1. It's great to see your improvements with the indicies.  Spring Batch doesn't provide indicies because user's usages vary so we leave database optimizations to the users.  That being said, SCDF and the CTR have more opinionated use cases so maybe adding some indices when you use SCDF or CTR may make sense.  I believe we are planning on having an internal discussion about this. Stay tuned.
2.  For the memory perspective, while it's great that your use cases work well there, that may not be universal.  We need to be sure what the CTR and SCDF we provide are universal.
3.  As for the "bug" in the `TaskLifecycleListener`, that is not a bug and is by design.  The expectation of the `TaskLifecycleListener` is that it closes the parent `ApplicationContext`.  If we don't, if something like Tomcat was running in that parent context for Acutator end points, the app wouldn't shut down.  So this is working as it was designed.  We actually didn't design Spring Cloud Task to be used in an embedded mode.  The closest we get to that is by turning off the automatic closing of the context which is a feature we actually added to help with testing.  That being said, running a task in an embedded application could be useful.  If you open an issue in https://github.com/spring-cloud/spring-cloud-task we can talk about it there.
4. Finally I can understand your request as to the ability to register multiple CTR implementations with the same SCDF instance.  However, I'm not sure how that would look across the board.  How would you specify which CTR to use in a task definition?  For example, right now when using the shell, you'd do something like: `task create my-composed-task --definition "<task1 || task2 > && <task3 || task4 || task5>"`.  What would the new version of the shell command look like?

**Comment by cppwfs** [comment] 2018-07-05 20:00
> For issue 4:  You can always register your own CTR app as a task and pass in the DSL via the --graph property when you create the definition.   It may not be as nice because you can't use the UI designer, but it does work.

**Comment by mminella** [comment] 2018-07-06 15:32
So what does that look like from a consumption perspective?  What does the shell command look like when you have more than one CTR configured?

**Comment by jvmlet** [comment] 2018-07-08 04:59
1. Register both OOTB and custom CTR :
````
app register --name composed-task-runner --type task --uri maven://org.springframework.cloud.task.app:composedtaskrunner-task:1.1.1.RELEASE
app register --name my-custom-composed-task-runner --type task --uri maven://com.company:custom-composedtaskrunner-task:1.0.0.RELEASE
````
2. Create composed task as usual :
`
task create my-composed-task --definition "<task1 || task2 > && <task3 || task4 || task5>"
`
3. Launch with default `composed-task-runner` runner :
`
task launch --name TEST_PIPELINE 
`
4. Launch with custom `my-custom-composed-task-runner` runner :
`
task launch --name TEST_PIPELINE --runner-name my-custom-composed-task-runner
`

The `TaskExecutionController`'s `launch` method should be added the optional `runnerName` request parameter

````java
@RequestMapping(value = "", method = RequestMethod.POST, params = "name")
	@ResponseStatus(HttpStatus.CREATED)
	public long launch(@RequestParam("name") String taskName, 
                            @RequestParam(value="name",required = false) String runnerName, 
                             @RequestParam(required = false) String properties,
	                @RequestParam(required = false) List<String> arguments) {
//propagate the runnerName to underlying taskService  :
   taskService.executeTask(taskName,runnerName,......)
	}
````

The dashboard UI to launch the task will also need to support `runner-name` parameter.

The custom implementation of CTR will  follow the same contract and properties/arguments propagation  logic as OOTB CTR.

**Comment by cppwfs** [comment] 2019-06-28 16:20
I had a chance to play with this issue, this morning.    We will need to alter the Task-Execution Table to store the ctr that was used to launch the task.   This is to support restarting a failed CTR execution, because at this time we don't have a way to know what CTR was used when the task was launched. 
 This table alter can be done within dataflow.

**Closed** 2019-07-22 17:36 UTC
Labels: composed-tasks, enhancement
