### ISSUE TITLE
CommonApplicationProperties are not passed as parameter to starting tasks

### ISSUE THREAD

**Issue by michael-wirth** [spring-cloud/spring-cloud-dataflow#2124] opened 2018-03-28 19:31 UTC
According to the [documentation (chapter 46.4.1)](https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_common_application_properties) common application properties should be passed to the launching tasks.

For exmaple the following definition should pass the kafka broker to all tasks:
`--spring.cloud.dataflow.applicationProperties.task.spring.cloud.stream.kafka.binder.brokers=kafka:9092
`

but the [DefaultTaskService](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskService.java#L287) filters the properties with a prefix ("app." + registeredAppName), meaning the properties are not passed to the starting tasks.

This works different for CcommonApplicationProperties for Streams. Is this the expected behavior?

I tested it with DataFlowServerLocal Version 1.3.0.

**Comment by cppwfs** [comment] 2018-03-28 20:05
This looks to be a duplicate of https://github.com/spring-cloud/spring-cloud-dataflow/issues/1531  Which was fixed in the 1.4.x release and backported to the 1.3.x line via PR https://github.com/spring-cloud/spring-cloud-dataflow/pull/2070.

**Closed by cppwfs** 2018-03-28 20:05 UTC

**Comment by michael-wirth** [comment] 2018-04-08 07:57
@cppwfs But this is not working as described in the documentation. 
**I can't define some global properties for all tasks.** 

The fix expects that all properties must be prefixed with e.g. `app.mytask` and therefore the property is applied to only **1** task. Is that the expected behaviour? if this is not a bug then the documentation should be updated, as you clearly need to prefix your properties with the taskname to pass them to the launching task. also the implementation shows clearly that not all properties are passed throught, as the properties are filtered by the prefix as described in my original post.

I tested it with `spring-cloud-dataflow-server-local-1.4.0.RELEASE.jar`.

btw. What is the expected solution to pass config-server-uri and kafka broker uri to all launching task?
