### ISSUE TITLE
Request for V3 API Support in Spring Cloud Data Flow Server to Avoid CF-RateLimitV2APIExceeded Error

### ISSUE THREAD

**Issue by DanFrei** [spring-cloud/spring-cloud-dataflow#5951] opened 2024-09-23 15:18 UTC
**Description:**
We at SAP, are encountering the following error while deploying tasks using Spring Cloud Data Flow Server:
`CF-RateLimitV2APIExceeded(10018): Rate Limit of V2 API Exceeded. Please consider using the V3 API.`

This error occurs because **SAP Cloud Foundry** has deprecated the V2 API, and its usage is now rate-limited as part of the **SAP CF API v2 Deprecation and Removal Plan**. However, Spring Cloud Data Flow Server still relies on the V2 API via the [Spring Deployer](https://github.com/spring-cloud/spring-cloud-deployer/issues/479), which appears to be hardcoded, and there is no way to configure the server to use the **V3 API**
The deprecation of the V2 API and subsequent rate-limiting severely impacts task deployments, causing delays and failures in our pipeline.

Could you please provide a fix that would make it configurable?

**Release versions:**
Name: spring-cloud-dataflow-server
Version: 2.11.3
Commit: [2183849](https://github.com/spring-cloud/spring-cloud-dataflow/commit/2183849)

**Screenshots:**
<img width="767" alt="Screenshot 2024-09-23 at 18 18 12" src="https://github.com/user-attachments/assets/7ab8ff56-a81f-4fc8-b3fa-3688be08f345">

**Comment by cppwfs** [comment] 2024-09-24 16:18
Related to: https://github.com/spring-cloud/spring-cloud-deployer/issues/479

**Comment by cppwfs** [comment] 2024-09-30 13:14
Closing this as a duplicate of : https://github.com/spring-cloud/spring-cloud-deployer/issues/479

**Closed by cppwfs** 2024-09-30 13:14 UTC
Labels: status/need-triage
