### ISSUE TITLE
Plus signs are replaced with spaces in task launcher properties provided via UI

### ISSUE THREAD

**Issue by einmartwa** [spring-cloud/spring-cloud-dataflow#4728] opened 2021-10-20 12:12 UTC
**Description:**
When providing additional properties to a task launch via the UI, plus signs within Strings passed are replaced by spaces.

**Release versions:**
SCDF v2.9.0, see JSON below

**Steps to reproduce:**
1. Start up Spring Cloud Data Flow (2.9.0), e.g. via spring-boot:run locally, with spring.cloud.dataflow.features.tasks-enabled=true in the config
2. Register any app, in the snapshots called "my-test-app"
3. Register any task, in the snapshots called "my-test-task", which just runs "my-test-app"
4. In the UI, go to "Tasks", choose your task, and press "Launch Task"
5. Provide some properties to the tasks that contain plus signs, e.g. by going to "Freetext" and entering 
deployer.my-test-task.kubernetes.environmentVariables=MY_ENV_PLUS='MY+ENV+WITH+PLUS',MY_ENV_SPECIAL_CHARS='!@#$%^&*()_+_ENV'
6. Launch the task
7. Check the task execution and its environment variables, e.g. go to "Tasks executions", check the latest execution of your task and validate that the Strings passed have all plus signs replaced by spaces.

**Screenshots:**
Snapshot of properties passed via launch config
![launch_config](https://user-images.githubusercontent.com/92861634/138089052-28c13688-16f1-4391-9c0c-f9e6c0c0e489.PNG)
Snapshot of the resulting properties passed to the task, all plus signs are replaced by spaces
![failed_envs](https://user-images.githubusercontent.com/92861634/138089119-1cc19d5d-e8ad-4e3b-b82f-67bff141c4a3.PNG)

**Additional context:**
This issue did first appear on a Cloud deployment on Linux machines, so it should not be Win10-related.
We typically pass such configuration via REST calls (using DataFlowOperations), which is not affected by this.
Then, the first launch succeeds, but when restarting the now pre-configured task via UI the issue occurs.
I also checked the "task_execution_metadata" table which contains a proper manifest entry after a REST-based launch and a broken entry after a UI-based launch.

**Release Information**
{
  "versions": {
    "implementation": {
      "name": "spring-cloud-dataflow-server",
      "version": "2.9.0"
    },
    "core": {
      "name": "Spring Cloud Data Flow Core",
      "version": "2.9.0"
    },
    "dashboard": {
      "name": "Spring Cloud Dataflow UI",
      "version": "3.2.0"
    },
    "shell": {
      "name": "Spring Cloud Data Flow Shell",
      "version": "2.9.0",
      "url": "https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.9.0/spring-cloud-dataflow-shell-2.9.0.jar"
    }
  },
  "features": {
    "streams": false,
    "tasks": true,
    "schedules": true,
    "monitoringDashboardType": "NONE"
  },
  "runtimeEnvironment": {
    "appDeployer": {
      "deployerImplementationVersion": null,
      "deployerName": null,
      "deployerSpiVersion": null,
      "javaVersion": null,
      "platformApiVersion": null,
      "platformClientVersion": null,
      "platformHostVersion": null,
      "platformSpecificInfo": {},
      "platformType": null,
      "springBootVersion": null,
      "springVersion": null
    },
    "taskLaunchers": [
      {
        "deployerImplementationVersion": "2.7.0",
        "deployerName": "LocalTaskLauncher",
        "deployerSpiVersion": "2.7.0",
        "javaVersion": "11.0.9",
        "platformApiVersion": "Windows 10 10.0",
        "platformClientVersion": "10.0",
        "platformHostVersion": "10.0",
        "platformSpecificInfo": {},
        "platformType": "Local",
        "springBootVersion": "2.5.5",
        "springVersion": "5.3.10"
      }
    ]
  },
  "monitoringDashboardInfo": {
    "url": "",
    "source": "default-scdf-source",
    "refreshInterval": 15
  },
  "security": {
    "isAuthentication": false,
    "isAuthenticated": false,
    "username": null,
    "roles": []
  }
}

**Comment by cppwfs** [comment] 2021-11-04 16:07
Closing the UI side.   This appears to  be a server side issue in how it handles the +.   
Currently when the controller receives the property the controller is converting the `+` to a ` `.   And when I try to replace it with `%2B` the controller doesn't convert it to a`+` it leaves it as `%2B`.    Closing the UI issue.

**Comment by onobc** [comment] 2022-02-08 23:55
This is caused by the incoming query params not being URL encoded. The server expects them to be and it does a URL decode of them (which is a good default stance).

Here is an example.

#### Start SCDF locally
```bash
cd <SCDF-REPO-DIR>
./mvn clean install -DskipTests
java -jar spring-cloud-dataflow-server/target/spring-cloud-dataflow-server-2.9.3-SNAPSHOT.jar
```

#### Create / Launch Task in UI
- http://localhost:9393/dashboard/#/apps/add
  - import "Task application starters for Docker" apps 
- http://localhost:9393/dashboard/#/tasks-jobs/tasks
   - create a task using `timestamp`
- http://localhost:9393/dashboard/#/tasks-jobs/tasks/tiempo/launch
   - use app properties "foo" = "51+50"

You can see on the server-side logs it comes in as `"foo":"51 50".`

> 2022-02-08 17:45:05.605  INFO 7901 --- [nio-9393-exec-1] o.s.c.d.spi.local.LocalTaskLauncher      : Command to be executed: docker run --network bridge --rm -e deployerId=tiempo-19753e34-5e95-461e-8237-ebd5c5c1dec9 -e SPRING_APPLICATION_JSON={"management.metrics.tags.service":"task-application","endpoints.jmx.unique-names":"true","endpoints.shutdown.enabled":"true","spring.datasource.username":"sa","spring.datasource.url":"jdbc:h2:tcp://localhost:19092/mem:dataflow","spring.datasource.driverClassName":"org.h2.Driver","management.metrics.tags.application":"${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}","foo":"51 50","server.port":"25508","spring.cloud.task.name":"tiempo","spring.jmx.default-domain":"tiempo-19753e34-5e95-461e-8237-ebd5c5c1dec9"} -p 25508:25508 springcloudtask/timestamp-task:2.1.1.RELEASE --spring.cloud.task.executionid=1

Now relaunch using curl and encode the parameter (`"+" = "%2B"`)

```
curl 'http://localhost:9393/tasks/executions?name=tiempo&properties=app.timestamp.foo=51%2B50' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"' \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'Origin: http://localhost:9393' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:9393/dashboard/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  -H 'Cookie: JSESSIONID=C074222EEB1A862B151BFDCEF234A539' \
  --data-raw '{}' \
  --compressed
```

You can see on the server-side logs it NOW comes in as `"foo":"51+50"`

> 2022-02-08 17:45:53.509  INFO 7901 --- [nio-9393-exec-6] o.s.c.d.spi.local.LocalTaskLauncher      : Command to be executed: docker run --network bridge --rm -e deployerId=tiempo-2e0bdafb-eb15-43de-83a9-3f63d5278f2b -e SPRING_APPLICATION_JSON={"management.metrics.tags.service":"task-application","endpoints.jmx.unique-names":"true","endpoints.shutdown.enabled":"true","spring.datasource.username":"sa","spring.datasource.url":"jdbc:h2:tcp://localhost:19092/mem:dataflow","spring.datasource.driverClassName":"org.h2.Driver","management.metrics.tags.application":"${spring.cloud.task.name:unknown}-${spring.cloud.task.executionid:unknown}","foo":"51+50","server.port":"55380","spring.cloud.task.name":"tiempo","spring.jmx.default-domain":"tiempo-2e0bdafb-eb15-43de-83a9-3f63d5278f2b"} -p 55380:55380 springcloudtask/timestamp-task:2.1.1.RELEASE --spring.cloud.task.executionid=2


While we could modify all of our REST controllers to manually decode the query params (direct access to HttpServletRequest.getQueryString()) this would likely introduce other encoding/url issues. I believe we should adjust the UI to always encode our query params.

**Comment by onobc** [comment] 2022-02-22 14:56
Fixed via https://github.com/spring-cloud/spring-cloud-dataflow-ui/pull/1827

**Closed by onobc** 2022-02-22 14:56 UTC
Labels: type/bug
