### ISSUE TITLE
Composed task arguments are not passed after job restart

### ISSUE THREAD

**Issue by mathansakthi** [spring-cloud/spring-cloud-dataflow#2857] opened 2019-02-06 02:09 UTC
I'm running a composed task with three child tasks.

Composed task definition:
`task create  --definition='task1 && task2 && task3'`

Launch command:
`task launch my-composed-task --properties "app.composed-task-runner.composed-task-arguments=arg1=a.txt arg2=test"
`
Scenario 1: when the composed task runs without any error, the arguments are passed to all child tasks.

Scenario 2: when the second child task fails and if the job is restarted , the composed task arguments are passed to second child task but not to third child task

Scenario 3 :
when the first and second tasks succeed and third child task fails and if the job is restarted , the composed task arguments are now passed to third child task.

Observation: After a task failure and restart, the composed-task-arguments are passed only to the failed task and not to the tasks after that.

This occurs even with simple spring cloud task application.

Version used :
`Spring cloud local server - 1.7.3 , Spring boot - 2.0.4 , Spring cloud starter task - 2.0.0`

**Comment by sabbyanandan** [comment] 2019-02-06 02:19
Hi, @mathansakthi. This appears to be a duplicate of [StackOverflow thread](https://stackoverflow.com/questions/54521651/composed-task-arguments-are-not-passed-after-job-restart). We are reviewing it on our side; we will get back to you on the post. cc/ @cppwfs

**Closed by sabbyanandan** 2019-02-06 02:19 UTC
Labels: question 🤔
